/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import {
  GetContactsResponse,
  GetContactsResponseFromJSON,
  GetContactsResponseToJSON,
} from '../models'

/**
 *
 */
export class ContactApi extends runtime.BaseAPI {
  /**
   * Получение контактов
   */
  async getContactsRaw(): Promise<runtime.ApiResponse<GetContactsResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/contacts-v1`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    })

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetContactsResponseFromJSON(jsonValue),
    )
  }

  /**
   * Получение контактов
   */
  async getContacts(): Promise<GetContactsResponse> {
    const response = await this.getContactsRaw()
    return await response.value()
  }
}
