/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import { GetMenuResponse, GetMenuResponseFromJSON, GetMenuResponseToJSON } from '../models'

/**
 *
 */
export class MenuApi extends runtime.BaseAPI {
  /**
   * Получение дерева списков активных меню
   */
  async getMenuRaw(): Promise<runtime.ApiResponse<GetMenuResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/menus-v1`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    })

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetMenuResponseFromJSON(jsonValue),
    )
  }

  /**
   * Получение дерева списков активных меню
   */
  async getMenu(): Promise<GetMenuResponse> {
    const response = await this.getMenuRaw()
    return await response.value()
  }
}
