export const menus = {
  menu_desktop: [
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: '',
      images: null,
      items: [],
      prefix: null,
      slug: 'menu_desktop__sale',
      subtitle: null,
      suffix: null,
      title: 'Продать',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: '',
      images: null,
      items: [],
      prefix: null,
      slug: 'menu_desktop__exchange',
      subtitle: null,
      suffix: null,
      title: 'Обменять',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: '',
      images: null,
      items: [],
      prefix: null,
      slug: 'menu_desktop__buy',
      subtitle: null,
      suffix: null,
      title: 'Купить',
    },
  ],
  menu_mobile: [],
  policy: [
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: '/terms-of-use',
      images: null,
      items: [],
      prefix: null,
      slug: 'policy__terms',
      subtitle: null,
      suffix: null,
      title: 'Пользовательское соглашение',
    },
  ],
  social: [
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: 'https://api.whatsapp.com/send?phone=74952522255&text=',
      images: null,
      items: [],
      prefix: null,
      slug: 'social__Facebook',
      subtitle: null,
      suffix: null,
      title: 'Facebook',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: 'https://api.whatsapp.com/send?phone=74952522255&text=',
      images: null,
      items: [],
      prefix: null,
      slug: 'social__VK',
      subtitle: null,
      suffix: null,
      title: 'VK',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: 'https://api.whatsapp.com/send?phone=74952522255&text=',
      images: null,
      items: [],
      prefix: null,
      slug: 'social__Instagram',
      subtitle: null,
      suffix: null,
      title: 'Instagram',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: 'https://api.whatsapp.com/send?phone=74952522255&text=',
      images: null,
      items: [],
      prefix: null,
      slug: 'social__whatsapp',
      subtitle: null,
      suffix: null,
      title: 'WhatsApp',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: 'tg://resolve?domain=PIK_Broker_bot',
      images: null,
      items: [],
      prefix: null,
      slug: 'social__telegram',
      subtitle: null,
      suffix: null,
      title: 'Telegram',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: 'https://api.whatsapp.com/send?phone=74952522255&text=',
      images: null,
      items: [],
      prefix: null,
      slug: 'social__OK',
      subtitle: null,
      suffix: null,
      title: 'OK',
    },
    {
      attr: null,
      background: null,
      description: null,
      foreground: null,
      href: 'https://api.whatsapp.com/send?phone=74952522255&text=',
      images: null,
      items: [],
      prefix: null,
      slug: 'social__Почта',
      subtitle: null,
      suffix: null,
      title: 'Почта',
    },
  ],
}
