#!/usr/bin/env sh

ENV_FILE_DEPLOY=.env.deploy_staging

echo "Building ${ENV_FILE_DEPLOY} file"
echo "BACKEND_PROXY_PASS=${BACKEND_URL}" > "${ENV_FILE_DEPLOY}"
echo "API_ORIGIN=${BACKEND_URL}" >> "${ENV_FILE_DEPLOY}"
echo "NEXT_PUBLIC_USERPANEL_ORIGIN=${USERPANEL_URL}" >> "${ENV_FILE_DEPLOY}"
echo "NEXT_PUBLIC_GTM_ID=${GTM_ID}" >> "${ENV_FILE_DEPLOY}"
echo "NEXT_PUBLIC_APP_ENV=${APP_ENV}" >> "${ENV_FILE_DEPLOY}"
echo "NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}" >> "${ENV_FILE_DEPLOY}"
echo "NEXT_PUBLIC_IMG_PROXY_URL=${IMG_PROXY_URL}" >> "${ENV_FILE_DEPLOY}"
echo "NEXT_PUBLIC_BRAND=${BRAND}" >> "${ENV_FILE_DEPLOY}"
echo "NEXT_PUBLIC_UISCOM=${UISCOM}" >> "${ENV_FILE_DEPLOY}"
echo "SENTRY_RELEASE=${SENTRY_RELEASE}" >> "${ENV_FILE_DEPLOY}"
echo ""
echo "${ENV_FILE_DEPLOY}"
cat "${ENV_FILE_DEPLOY}"
