- hosts: destination
  become: true

  roles:
    - role: staging2
      base_domain_name: kvarta.ru
      docker_compose_file: "deployment-docker-compose.yml"
      domains:
        - name: "kvarta.ru."
          tls_enabled:
            tls_fullchain: "/etc/letsencrypt/live/kvarta.ru/fullchain.pem"
            tls_key: "/etc/letsencrypt/live/kvarta.ru/privkey.pem"
          locations:
            - location: "/"
              port_name: "FRONTEND"
              allow_robots_x_tag: true
              disable_sha1_header: true
              disable_build_id_header: true
              disable_build_date_header: true
      dotenv_files:
        - src: ".env.deploy_staging"
          dst: ".env"
      owner_user: 1001
      owner_group: 1001
      rsync_options:
        - "--exclude=.git"
        - "--exclude=.yarn-cache"
      staging_application_env_file: ".env"
      static_staging: true
