import { SortBy, SortOrder } from '@/api'

export const SLUG = {
  '404': 'notFoundPage',
  APARTMENT: 'apartmentPage',
  CATALOG: 'catalogPage',
  CATALOG_ENTRY: 'catalogMainPage',
  CATALOG_MAP: 'catalogMapPage',
  INDEX: 'mainPage',
  LEGAL: 'legalPage',
  LEGAL_PERSONAL: 'personalLegalPage',
  LEGAL_PRIVACY: 'privacyLegalPage',
  NO_DISCOUNT: 'buyoutNoDiscountPage',
  MAIN_BUY: 'mainBuyPage',
  SALE: 'salePage',
  EXCHANGE: 'exchangePage',
  EXCHANGE_MAX: 'exchangeMaxPage',
  BUY: 'buyPage',
  TRADE_IN: 'tradeInPage',
} as const

export const CATALOG = {
  PAGE_INITIAL: 1,
  PER_PAGE: 10,
  SORT_BY_INITIAL: SortBy.CreatedAt,
  SORT_ORDER_INITIAL: SortOrder.Desc,
} as const

export const APARTMENTS_SIMILAR_LIMIT = 10 as const

export const NUMERIC_CONST = {
  DIFF_HEIGHT_WINDOW_AND_KEYBOARD: 130,
  MAX_ZOOM_ONCLICK: 12.5,
  DELAY_SET_BOUNDS: 400,
  ZOOM_FOR_CITY: 10,
  ZOOM_FOR_TOWN: 12,
} as const

export const STORAGE_KEY = 'pikb_entry_form_data'

export const FORM = {
  APARTMENT_FILTER: {
    APARTMENT_PLURAL: ['квартир', 'квартира', 'квартиры'],
    APARTMENT_PLURAL_FILTER: ['квартир', 'квартиру', 'квартиры'],
    SLUG_SALE_TRADEIN: 'trade_in_plus',
  },
  ERROR_UNDEFINED_MESSAGE: 'Произошла ошибка, попробуйте повторить позже',
  UNKNOWN_ERROR: 'Что-то пошло не так, попробуйте еще раз',
  LEAD: {
    SMS_INTERVAL: 1e3,
    SMS_TIMEOUT: 12e4,
    USER_NAME_MAXLENGTH: 100,
    USER_NAME_MAXLENGTH_MESSAGE: 'Пожалуйста, укоротите это текст до 100 символов или менее.',
    USER_NAME_MINLENGTH: 1,
    USER_NAME_MINLENGTH_MESSAGE: 'Пожалуйста, используйте не менее 1 символов.',
    USER_NAME_PATTERN: '^[\\s\\-A-Za-zЁА-яё]+$',
    USER_NAME_PATTERN_MESSAGE: 'Пожалуйста, используйте требуемый формат.',
    USER_NAME_REQUIRED: true,
    USER_NAME_REQUIRED_MESSAGE: 'Пожалуйста, заполните это поле.',
    USER_PHONE_MAXLENGTH: 17,
    USER_PHONE_MAXLENGTH_MESSAGE: 'Пожалуйста, укоротите это текст до 17 символов или менее.',
    USER_PHONE_MINLENGTH: 17,
    USER_PHONE_MINLENGTH_MESSAGE: 'Используйте формат: +7(000) 000-00-00.',
    USER_PHONE_LENGTH: 10,
    USER_PHONE_LENGTH_MESSAGE: 'Используйте формат: +7(000) 000-00-00.',
    USER_PHONE_PATTERN: '^\\+7\\(\\d{3}\\)\\s\\d{3}-\\d{2}-\\d{2}$',
    USER_PHONE_PATTERN_MESSAGE: 'Пожалуйста, используйте требуемый формат.',
    USER_PHONE_REQUIRED: true,
    USER_PHONE_REQUIRED_MESSAGE: 'Пожалуйста, заполните это поле.',
  },
} as const

export const PAGE = {
  ALIAS_404: '404',
  APARTMENT: {
    ERROR_INVALID_ID: 10,
    ERROR_WRONG_ID: 100,
    SLUG_HOUSING_PRIMARY: 'newbuilding',
    SLUG_HOUSING_SECONDARY: 'second',
    SLUG_SALE_FREE: 'svobodnaja',
    SLUG_SALE_TRADEIN: 'trade_in_plus',
    SLUG_TRAVEL_BYCAR: 'car',
    SLUG_TRAVEL_ONFOOT: 'peskom',
  },
  CATALOG: {
    PAGE_INITIAL: 1,
    SORT_BY_INITIAL: 'createdAt',
    SORT_ORDER_INITIAL: 'desc',
  },
  SLUG_404: 'notFoundPage',
  SLUG_APARTMENT: 'apartmentPage',
  SLUG_CATALOG: 'catalogPage',
  SLUG_CATALOG_ENTRY: 'catalogMainPage',
  SLUG_INDEX: 'mainPage',
  SLUG_LEGAL: 'legalPage',
  SLUG_LEGAL_PERSONAL: 'personalLegalPage',
  SLUG_LEGAL_PRIVACY: 'privacyLegalPage',
  SLUG_NODISCOUNT: 'buyoutNoDiscountPage',
} as const

export const SITE = {
  COOKIES_EXPIRES: 30,
} as const

export const COORDINATES_CITY = {
  Балашиха: [55.8094, 37.9581],
  Видное: [55.5524, 37.7097],
  Дзержинский: [55.6333, 37.8333],
  Долгопрудный: [55.9496, 37.5018],
  Домодедово: [55.4413, 37.7537],
  Железнодорожный: [55.744, 38.0168],
  Жуковский: [55.5953, 38.1203],
  Зеленоград: [55.9652, 37.1632],
  Ивантеевка: [55.9711, 37.9208],
  Королёв: [55.91417, 37.82556],
  Котельники: [55.63546, 37.8445],
  Красногорск: [55.82036, 37.33017],
  Лобня: [56.01723, 37.48526],
  Лыткарино: [55.58271, 37.90516],
  Люберцы: [55.67719, 37.89322],
  Москва: [55.751322, 37.617592],
  Московский: [55.5943, 37.322],
  Мытищи: [55.8918, 37.7481],
  Нахабино: [55.84854, 37.17788],
  Одинцово: [55.67798, 37.27773],
  Подольск: [55.42418, 37.55472],
  Пушкино: [56.01722, 37.86667],
  Раменское: [55.56694, 38.23028],
  Реутов: [55.76111, 37.8575],
  Троицк: [55.48722, 37.30465],
  Химки: [55.89704, 37.42969],
  Щелково: [55.925, 37.9722],
  Щербинка: [55.49972, 37.55972],
}

export type CoodinatesCityType = keyof typeof COORDINATES_CITY

export const listOfDocuments = {
  DKP: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Договор купли-продажи',
    'Реквизиты счета',
    'Акт приема-передачи',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
    'Платежное поручение об оплате',
  ],
  EXCHANGE: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Договор мены',
    'Реквизиты счета',
    'Акт приема-передачи',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
  ],
  DDU_PRIMARY: [
    'Паспорт',
    'Договор долевого участия',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Акт взаиморасчетов',
    'Справка о полной оплате по ДДУ',
    'Реквизиты счета',
  ],
  DDU_SECONDARY: [
    'Паспорт',
    'Договор долевого участия',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Акт взаиморасчетов',
    'Справка о полной оплате по ДДУ',
    'Реквизиты счета',
    'АПП для ДДУ',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
  ],
  DUPT: [
    'Паспорт',
    'Справка о выплате пая',
    'Договор уступки прав требования',
    'Подтверждение расчетов по ДУПТ',
    'Акт взаиморасчетов',
  ],
  JSK: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Справка о выплате пая',
    'Реквизиты счета',
    'Акт приема-передачи',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
  ],
  RENT: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Свидетельсвто о смерти иждивенца',
    'Договор ренты',
    'Реквизиты счета',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
  ],
  DONATION: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Договор дарения',
    'Реквизиты счета',
    'Акт приема-передачи',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
    'Подтверждение родства',
    'Согласие дарителя на сделку',
  ],
  PRIVATIZATION: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Договор приватизации',
    'Реквизиты счета',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
    'Заявление к приватизации',
    'Отказ от приватизации',
    'Архивная выписка из домовой книги',
  ],
  INHERITANCE: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Свидетельство о наследстве',
    'Реквизиты счета',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
    'Отказ от наследства',
  ],
  COURT_DECISION: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Решение суда',
    'Реквизиты счета',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
  ],
  MARRIAGE_CONTRACT: [
    'Паспорт',
    'Выписка из ЕГРН/свидетельство о гос.регистрации права',
    'Брачный договор',
    'Реквизиты счета',
    'Квитанция ЖКУ за последний месяц',
    'Подтверждение оплаты ЖКУ',
    'Выписка из домовой книги',
    'Свидетельство о заключении брака',
    'Свидетельство о расторжении брака ',
  ],
  LOAN: [
    'Кредитный договор/договор займа',
    'Остаток долга по кредиту',
    'Уведомление Росреестра о погашении ипотеки',
    'Реквизиты для погашения ипотеки',
    'Справка из банка о полной оплате долга по кредитному договору (договору ипотеки)',
  ],
  MATERNAL_CAPITAL: ['Соглашение о выделении долей', 'Согласие опеки', 'Отказ супруга от доли'],
  MATERNAL_CAPITAL_DUPT_JSK: ['Соглашение о выделении долей', 'Согласие опеки'],
  MINORS: ['Согласие опеки', 'Свидетельство о рождении'],
  ENCUMBRANCES:
    'Квартира в залоге у банка МКБ. Обременение будет снято до перехода к Вам права собственности на квартиру. Гарантируем, что у третьих лиц не возникнет претензий к этому объекту после покупки',
}

export const INPUT_FORMATS = {
  INTEGER: {
    thousandSeparator: ' ',
    decimalScale: 0,
    allowNegative: false,
  },
  DECIMAL: {
    thousandSeparator: ' ',
    decimalSeparator: ',',
    allowNegative: false,
  },
}

export const LOCKED_APARTMENT_AMO_ID = 30929317
