import { config } from './config'

export const scripts = {
  ymaps: `window.addEventListener("load",function(){var e=document.createElement("script");e.setAttribute("crossorigin","anonymous"),e.setAttribute("id","ymaps"),e.setAttribute("src","https://api-maps.yandex.ru/2.1.78/?apikey=${config.ymapsApiKey}&lang=ru-RU"),e.addEventListener("error",function(e){console.error(e)}),e.addEventListener("load",function(e){console.info(e)}),document.body.append(e)});`,
  gtmInit: `window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);}`,
  gtm: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${config.gtmId}');`,
  gtmIframeSrc: `https://www.googletagmanager.com/ns.html?id=${config.gtmId}`,
  segmentStream: `window.digitalData={version:"1.1.3",website:{region:"Москва"}},function(e,t){t=t||"cdn.segmentstream.com";var n=window.segmentstream=window.segmentstream||[];window.ddListener=window.ddListener||[];var o=window.digitalData=window.digitalData||{};if(o.events=o.events||[],o.changes=o.changes||[],!n.initialize)if(n.invoked)window.console&&console.error&&console.error("SegmentStream snippet included twice.");else{for(n.invoked=!0,n.methods="initialize addIntegration persist unpersist on once off getConsent setConsent".split(" "),n.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);return t.unshift(e),n.push(t),n}},o=0;o<n.methods.length;o++){var s=n.methods[o];n[s]=n.factory(s)}n.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.charset="utf-8",t.async=!0,t.src=e,(e=document.getElementsByTagName("script")[0]).parentNode.insertBefore(t,e)},n.loadProject=function(e){var o=window.location.search;if(0<=o.indexOf("segmentstream_test_mode=1"))try{var s=!0;window.localStorage.setItem("_segmentstream_test_mode","1")}catch(e){}else if(0<=o.indexOf("segmentstream_test_mode=0"))try{s=!1,window.localStorage.removeItem("_segmentstream_test_mode")}catch(e){}else try{s="1"===window.localStorage.getItem("_segmentstream_test_mode")}catch(e){}s?n.load(window.SEGMENTSTREAM_TESTMODE_INIT_URL||"https://api.segmentstream.com/v1/project/"+e+".js"):n.load(window.SEGMENTSTREAM_INIT_URL||"https://"+t+"/project/"+e+".js")},n.CDN_DOMAIN=t,n.SNIPPET_VERSION="2.0.0",n.loadProject("${config.segmentStreamApiKey}")}}();`,
  sourcebuster: 'window.addEventListener("load",()=>{window.sbjs && window.sbjs.init()});',
}
