/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  AddressPoint,
  AddressPointFromJSON,
  AddressPointFromJSONTyped,
  AddressPointToJSON,
} from './'

/**
 * Адрес
 * @export
 * @interface Address
 */
export interface Address {
  /**
   * Отформатированная строка адреса
   * @type {string}
   * @memberof Address
   */
  formatted: string
  /**
   *
   * @type {AddressPoint}
   * @memberof Address
   */
  point: AddressPoint
}

export function AddressFromJSON(json: any): Address {
  return AddressFromJSONTyped(json, false)
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
  if (json === undefined || json === null) {
    return json
  }
  return {
    formatted: json['formatted'],
    point: AddressPointFromJSON(json['point']),
  }
}

export function AddressToJSON(value?: Address | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    formatted: value.formatted,
    point: AddressPointToJSON(value.point),
  }
}
