/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AddressPoint
 */
export interface AddressPoint {
  /**
   * Широта
   * @type {number}
   * @memberof AddressPoint
   */
  latitude: number
  /**
   * Долгота
   * @type {number}
   * @memberof AddressPoint
   */
  longitude: number
}

export function AddressPointFromJSON(json: any): AddressPoint {
  return AddressPointFromJSONTyped(json, false)
}

export function AddressPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressPoint {
  if (json === undefined || json === null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function AddressPointToJSON(value?: AddressPoint | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    latitude: value.latitude,
    longitude: value.longitude,
  }
}
