/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentsFilter,
  ApartmentsFilterFromJSON,
  ApartmentsFilterFromJSONTyped,
  ApartmentsFilterToJSON,
  ApartmentsFiltersBoundingBox,
  ApartmentsFiltersBoundingBoxFromJSON,
  ApartmentsFiltersBoundingBoxFromJSONTyped,
  ApartmentsFiltersBoundingBoxToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentMapRequest
 */
export interface ApartmentMapRequest {
  /**
   *
   * @type {ApartmentsFilter}
   * @memberof ApartmentMapRequest
   */
  filter?: ApartmentsFilter
  /**
   *
   * @type {ApartmentsFiltersBoundingBox}
   * @memberof ApartmentMapRequest
   */
  boundingBox: ApartmentsFiltersBoundingBox
}

export function ApartmentMapRequestFromJSON(json: any): ApartmentMapRequest {
  return ApartmentMapRequestFromJSONTyped(json, false)
}

export function ApartmentMapRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentMapRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    filter: !exists(json, 'filter') ? undefined : ApartmentsFilterFromJSON(json['filter']),
    boundingBox: ApartmentsFiltersBoundingBoxFromJSON(json['boundingBox']),
  }
}

export function ApartmentMapRequestToJSON(value?: ApartmentMapRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    filter: ApartmentsFilterToJSON(value.filter),
    boundingBox: ApartmentsFiltersBoundingBoxToJSON(value.boundingBox),
  }
}
