/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures,
  ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesFromJSON,
  ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesFromJSONTyped,
  ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentsMapResponseV2ResponseBodyObjectManager
 */
export interface ApartmentsMapResponseV2ResponseBodyObjectManager {
  /**
   *
   * @type {string}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManager
   */
  type?: ApartmentsMapResponseV2ResponseBodyObjectManagerTypeEnum
  /**
   *
   * @type {Array<ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures>}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManager
   */
  features?: Array<ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures>
}

/**
 * @export
 * @enum {string}
 */
export enum ApartmentsMapResponseV2ResponseBodyObjectManagerTypeEnum {
  FeatureCollection = 'FeatureCollection',
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerFromJSON(
  json: any,
): ApartmentsMapResponseV2ResponseBodyObjectManager {
  return ApartmentsMapResponseV2ResponseBodyObjectManagerFromJSONTyped(json, false)
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsMapResponseV2ResponseBodyObjectManager {
  if (json === undefined || json === null) {
    return json
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    features: !exists(json, 'features')
      ? undefined
      : (json['features'] as Array<any>).map(
          ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesFromJSON,
        ),
  }
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerToJSON(
  value?: ApartmentsMapResponseV2ResponseBodyObjectManager | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    type: value.type,
    features:
      value.features === undefined
        ? undefined
        : (value.features as Array<any>).map(
            ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesToJSON,
          ),
  }
}
