/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentsFilters,
  ApartmentsFiltersFromJSON,
  ApartmentsFiltersFromJSONTyped,
  ApartmentsFiltersToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentSearchRequestV1
 */
export interface ApartmentSearchRequestV1 {
  /**
   *
   * @type {ApartmentsFilters}
   * @memberof ApartmentSearchRequestV1
   */
  filter: ApartmentsFilters
}

export function ApartmentSearchRequestV1FromJSON(json: any): ApartmentSearchRequestV1 {
  return ApartmentSearchRequestV1FromJSONTyped(json, false)
}

export function ApartmentSearchRequestV1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentSearchRequestV1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    filter: ApartmentsFiltersFromJSON(json['filter']),
  }
}

export function ApartmentSearchRequestV1ToJSON(value?: ApartmentSearchRequestV1 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    filter: ApartmentsFiltersToJSON(value.filter),
  }
}
