/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentsMapResponseV2Response,
  ApartmentsMapResponseV2ResponseFromJSON,
  ApartmentsMapResponseV2ResponseFromJSONTyped,
  ApartmentsMapResponseV2ResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentsMapResponseV2
 */
export interface ApartmentsMapResponseV2 {
  /**
   *
   * @type {ApartmentsMapResponseV2Response}
   * @memberof ApartmentsMapResponseV2
   */
  response: ApartmentsMapResponseV2Response
}

export function ApartmentsMapResponseV2FromJSON(json: any): ApartmentsMapResponseV2 {
  return ApartmentsMapResponseV2FromJSONTyped(json, false)
}

export function ApartmentsMapResponseV2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsMapResponseV2 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: ApartmentsMapResponseV2ResponseFromJSON(json['response']),
  }
}

export function ApartmentsMapResponseV2ToJSON(value?: ApartmentsMapResponseV2 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: ApartmentsMapResponseV2ResponseToJSON(value.response),
  }
}
