/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentReference,
  ApartmentReferenceFromJSON,
  ApartmentReferenceFromJSONTyped,
  ApartmentReferenceToJSON,
  SubwayStation,
  SubwayStationFromJSON,
  SubwayStationFromJSONTyped,
  SubwayStationToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentSubwayStations
 */
export interface ApartmentSubwayStations {
  /**
   * Целое число минут, необходимое чтобы добраться до соответствующей станции метро способом travel
   * @type {number}
   * @memberof ApartmentSubwayStations
   */
  travelTimeToStation: number
  /**
   *
   * @type {ApartmentReference}
   * @memberof ApartmentSubwayStations
   */
  travel: ApartmentReference | null
  /**
   *
   * @type {SubwayStation}
   * @memberof ApartmentSubwayStations
   */
  station: SubwayStation
}

export function ApartmentSubwayStationsFromJSON(json: any): ApartmentSubwayStations {
  return ApartmentSubwayStationsFromJSONTyped(json, false)
}

export function ApartmentSubwayStationsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentSubwayStations {
  if (json === undefined || json === null) {
    return json
  }
  return {
    travelTimeToStation: json['travelTimeToStation'],
    travel: ApartmentReferenceFromJSON(json['travel']),
    station: SubwayStationFromJSON(json['station']),
  }
}

export function ApartmentSubwayStationsToJSON(value?: ApartmentSubwayStations | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    travelTimeToStation: value.travelTimeToStation,
    travel: ApartmentReferenceToJSON(value.travel),
    station: SubwayStationToJSON(value.station),
  }
}
