/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ApartmentsFiltersBoundingBox
 */
export interface ApartmentsFiltersBoundingBox {
  /**
   *
   * @type {number}
   * @memberof ApartmentsFiltersBoundingBox
   */
  lowLeftLong: number
  /**
   *
   * @type {number}
   * @memberof ApartmentsFiltersBoundingBox
   */
  lowLeftLat: number
  /**
   *
   * @type {number}
   * @memberof ApartmentsFiltersBoundingBox
   */
  upRightLong: number
  /**
   *
   * @type {number}
   * @memberof ApartmentsFiltersBoundingBox
   */
  upRightLat: number
}

export function ApartmentsFiltersBoundingBoxFromJSON(json: any): ApartmentsFiltersBoundingBox {
  return ApartmentsFiltersBoundingBoxFromJSONTyped(json, false)
}

export function ApartmentsFiltersBoundingBoxFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsFiltersBoundingBox {
  if (json === undefined || json === null) {
    return json
  }
  return {
    lowLeftLong: json['lowLeftLong'],
    lowLeftLat: json['lowLeftLat'],
    upRightLong: json['upRightLong'],
    upRightLat: json['upRightLat'],
  }
}

export function ApartmentsFiltersBoundingBoxToJSON(
  value?: ApartmentsFiltersBoundingBox | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    lowLeftLong: value.lowLeftLong,
    lowLeftLat: value.lowLeftLat,
    upRightLong: value.upRightLong,
    upRightLat: value.upRightLat,
  }
}
