/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentsMapResponseV2ResponseBodyObjectManager,
  ApartmentsMapResponseV2ResponseBodyObjectManagerFromJSON,
  ApartmentsMapResponseV2ResponseBodyObjectManagerFromJSONTyped,
  ApartmentsMapResponseV2ResponseBodyObjectManagerToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentsMapResponseV2ResponseBody
 */
export interface ApartmentsMapResponseV2ResponseBody {
  /**
   *
   * @type {ApartmentsMapResponseV2ResponseBodyObjectManager}
   * @memberof ApartmentsMapResponseV2ResponseBody
   */
  objectManager?: ApartmentsMapResponseV2ResponseBodyObjectManager
}

export function ApartmentsMapResponseV2ResponseBodyFromJSON(
  json: any,
): ApartmentsMapResponseV2ResponseBody {
  return ApartmentsMapResponseV2ResponseBodyFromJSONTyped(json, false)
}

export function ApartmentsMapResponseV2ResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsMapResponseV2ResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    objectManager: !exists(json, 'ObjectManager')
      ? undefined
      : ApartmentsMapResponseV2ResponseBodyObjectManagerFromJSON(json['ObjectManager']),
  }
}

export function ApartmentsMapResponseV2ResponseBodyToJSON(
  value?: ApartmentsMapResponseV2ResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ObjectManager: ApartmentsMapResponseV2ResponseBodyObjectManagerToJSON(value.objectManager),
  }
}
