/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ApartmentRoominess
 */
export interface ApartmentRoominess {
  /**
   * Является-ли квартира студией
   * @type {boolean}
   * @memberof ApartmentRoominess
   */
  isStudio?: boolean
  /**
   * Количество комнат в квартире. Учитывается только если isStudio == false
   * @type {number}
   * @memberof ApartmentRoominess
   */
  count?: number | null
  /**
   *
   * @type {Array<number>}
   * @memberof ApartmentRoominess
   */
  area?: Array<number> | null
}

export function ApartmentRoominessFromJSON(json: any): ApartmentRoominess {
  return ApartmentRoominessFromJSONTyped(json, false)
}

export function ApartmentRoominessFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentRoominess {
  if (json === undefined || json === null) {
    return json
  }
  return {
    isStudio: !exists(json, 'isStudio') ? undefined : json['isStudio'],
    count: !exists(json, 'count') ? undefined : json['count'],
    area: !exists(json, 'area') ? undefined : json['area'],
  }
}

export function ApartmentRoominessToJSON(value?: ApartmentRoominess | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    isStudio: value.isStudio,
    count: value.count,
    area: value.area,
  }
}
