/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  Address,
  AddressFromJSON,
  AddressFromJSONTyped,
  AddressToJSON,
  ApartmentImages,
  ApartmentImagesFromJSON,
  ApartmentImagesFromJSONTyped,
  ApartmentImagesToJSON,
  ApartmentReference,
  ApartmentReferenceFromJSON,
  ApartmentReferenceFromJSONTyped,
  ApartmentReferenceToJSON,
  ApartmentRoominess,
  ApartmentRoominessFromJSON,
  ApartmentRoominessFromJSONTyped,
  ApartmentRoominessToJSON,
  ApartmentSubwayStations,
  ApartmentSubwayStationsFromJSON,
  ApartmentSubwayStationsFromJSONTyped,
  ApartmentSubwayStationsToJSON,
  ApartmentVideos,
  ApartmentVideosFromJSON,
  ApartmentVideosFromJSONTyped,
  ApartmentVideosToJSON,
} from './'

/**
 *
 * @export
 * @interface Apartment
 */
export interface Apartment {
  /**
   * Уникальный идентификатор UUID версии 4
   * @type {string}
   * @memberof Apartment
   */
  uuid: string
  /**
   * Идентификатор в АМО. На сайте будет использоваться как артикул
   * @type {number}
   * @memberof Apartment
   */
  amoId: number
  /**
   *
   * @type {Address}
   * @memberof Apartment
   */
  address: Address
  /**
   * Станции метро
   * @type {Array<ApartmentSubwayStations>}
   * @memberof Apartment
   */
  subwayStations: Array<ApartmentSubwayStations>
  /**
   *
   * @type {Array<ApartmentVideos>}
   * @memberof Apartment
   */
  videos: Array<ApartmentVideos>
  /**
   *
   * @type {Array<ApartmentImages>}
   * @memberof Apartment
   */
  images: Array<ApartmentImages>
  /**
   *
   * @type {ApartmentRoominess}
   * @memberof Apartment
   */
  roominess: ApartmentRoominess
  /**
   * Количество балконов в квартире
   * @type {number}
   * @memberof Apartment
   */
  balconiesCount: number
  /**
   * Количество лоджий в квартире
   * @type {number}
   * @memberof Apartment
   */
  loggiasCount: number | null
  /**
   * Количество совмещенных санузлов
   * @type {number}
   * @memberof Apartment
   */
  combinedWcsCount: number
  /**
   * Количество раздельных санузлов
   * @type {number}
   * @memberof Apartment
   */
  separateWcsCount: number
  /**
   * Этаж квартиры
   * @type {number}
   * @memberof Apartment
   */
  floorNumber: number
  /**
   * Полная площадь квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  fullArea: number
  /**
   * Жилая площадь квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  livingArea: number | null
  /**
   * Площадь кухни квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  kitchensArea: number | null
  /**
   * Суммарная площадь балконов и лоджий квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  balconiesAndLoggiasArea: number | null
  /**
   * Суммарная площадь спален квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  bedroomsArea: number | null
  /**
   * Суммарная площадь ванных комнат квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  bathroomsArea: number | null
  /**
   * Суммарная площадь туалетов квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  wcsArea: number | null
  /**
   * Суммарная площадь прихожих квартиры в квадратных дециметрах
   * @type {number}
   * @memberof Apartment
   */
  hallwaysArea: number | null
  /**
   * Стоимость квартиры в рублях без копеек
   * @type {number}
   * @memberof Apartment
   */
  priceRub: number
  /**
   * Серия здания
   * @type {string}
   * @memberof Apartment
   */
  buildingSeries: string | null
  /**
   * Год постройки здания
   * @type {number}
   * @memberof Apartment
   */
  buildingConstructionYear: number
  /**
   * Коментарий к году постройки здания
   * @type {string}
   * @memberof Apartment
   */
  buildingConstructionYearComment: string | null
  /**
   * Количество этажей в здании
   * @type {number}
   * @memberof Apartment
   */
  buildingFloorCount: number
  /**
   * Высота потолков в здании в сантиметрах
   * @type {number}
   * @memberof Apartment
   */
  buildingCeilingHeight: number | null
  /**
   * Количество пассажирских лифтов в здании
   * @type {number}
   * @memberof Apartment
   */
  buildingPassengerElevatorsCount: number | null
  /**
   * Количество грузовых лифтов в здании
   * @type {number}
   * @memberof Apartment
   */
  buildingFreightElevatorsCount: number | null
  /**
   * Наличие мусоропровода в здании
   * @type {boolean}
   * @memberof Apartment
   */
  isBuildingHasGarbageChute: boolean | null
  /**
   * Количество подъездов в здании
   * @type {number}
   * @memberof Apartment
   */
  buildingPorchsCount: number | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  buildingType: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  buildingParkingType: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  buildingDeveloper: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  housingComplex: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  housingComplexBuilding: ApartmentReference | null
  /**
   * Типы продажи
   * @type {Array<ApartmentReference>}
   * @memberof Apartment
   */
  saleTypes: Array<ApartmentReference>
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  housingType: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  decorationType: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  heatingType: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  roomType: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  stoveType: ApartmentReference | null
  /**
   *
   * @type {ApartmentReference}
   * @memberof Apartment
   */
  windowViewType: ApartmentReference | null
  /**
   * Номер телефона для обращений по квартире
   * @type {string}
   * @memberof Apartment
   */
  contactPhoneNumber: string
  /**
   * Наличие перепланировки
   * @type {boolean}
   * @memberof Apartment
   */
  isRedevelopment: boolean | null
  /**
   * Ставка по ипотеке по базовым параметрам
   * @type {number}
   * @memberof Apartment
   */
  loanRate: number | null
  /**
   * Скидка на квартиру
   * @type {number}
   * @memberof Apartment
   */
  discountRate: number | null
  /**
   * Статус квартиры: listed = актуальна, unlisted = продана
   * @type {string}
   * @memberof Apartment
   */
  statusLabel?: ApartmentStatusLabelEnum
}

/**
 * @export
 * @enum {string}
 */
export enum ApartmentStatusLabelEnum {
  Listed = 'listed',
  Unlisted = 'unlisted',
}

export function ApartmentFromJSON(json: any): Apartment {
  return ApartmentFromJSONTyped(json, false)
}

export function ApartmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Apartment {
  if (json === undefined || json === null) {
    return json
  }
  return {
    uuid: json['uuid'],
    amoId: json['amoId'],
    address: AddressFromJSON(json['address']),
    subwayStations: (json['subwayStations'] as Array<any>).map(ApartmentSubwayStationsFromJSON),
    videos: (json['videos'] as Array<any>).map(ApartmentVideosFromJSON),
    images: (json['images'] as Array<any>).map(ApartmentImagesFromJSON),
    roominess: ApartmentRoominessFromJSON(json['roominess']),
    balconiesCount: json['balconiesCount'],
    loggiasCount: json['loggiasCount'],
    combinedWcsCount: json['combinedWcsCount'],
    separateWcsCount: json['separateWcsCount'],
    floorNumber: json['floorNumber'],
    fullArea: json['fullArea'],
    livingArea: json['livingArea'],
    kitchensArea: json['kitchensArea'],
    balconiesAndLoggiasArea: json['balconiesAndLoggiasArea'],
    bedroomsArea: json['bedroomsArea'],
    bathroomsArea: json['bathroomsArea'],
    wcsArea: json['wcsArea'],
    hallwaysArea: json['hallwaysArea'],
    priceRub: json['priceRub'],
    buildingSeries: json['buildingSeries'],
    buildingConstructionYear: json['buildingConstructionYear'],
    buildingConstructionYearComment: json['buildingConstructionYearComment'],
    buildingFloorCount: json['buildingFloorCount'],
    buildingCeilingHeight: json['buildingCeilingHeight'],
    buildingPassengerElevatorsCount: json['buildingPassengerElevatorsCount'],
    buildingFreightElevatorsCount: json['buildingFreightElevatorsCount'],
    isBuildingHasGarbageChute: json['isBuildingHasGarbageChute'],
    buildingPorchsCount: json['buildingPorchsCount'],
    buildingType: ApartmentReferenceFromJSON(json['buildingType']),
    buildingParkingType: ApartmentReferenceFromJSON(json['buildingParkingType']),
    buildingDeveloper: ApartmentReferenceFromJSON(json['buildingDeveloper']),
    housingComplex: ApartmentReferenceFromJSON(json['housingComplex']),
    housingComplexBuilding: ApartmentReferenceFromJSON(json['housingComplexBuilding']),
    saleTypes: (json['saleTypes'] as Array<any>).map(ApartmentReferenceFromJSON),
    housingType: ApartmentReferenceFromJSON(json['housingType']),
    decorationType: ApartmentReferenceFromJSON(json['decorationType']),
    heatingType: ApartmentReferenceFromJSON(json['heatingType']),
    roomType: ApartmentReferenceFromJSON(json['roomType']),
    stoveType: ApartmentReferenceFromJSON(json['stoveType']),
    windowViewType: ApartmentReferenceFromJSON(json['windowViewType']),
    contactPhoneNumber: json['contactPhoneNumber'],
    isRedevelopment: json['isRedevelopment'],
    loanRate: json['loanRate'],
    discountRate: json['discountRate'],
    statusLabel: !exists(json, 'statusLabel') ? undefined : json['statusLabel'],
  }
}

export function ApartmentToJSON(value?: Apartment | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    uuid: value.uuid,
    amoId: value.amoId,
    address: AddressToJSON(value.address),
    subwayStations: (value.subwayStations as Array<any>).map(ApartmentSubwayStationsToJSON),
    videos: (value.videos as Array<any>).map(ApartmentVideosToJSON),
    images: (value.images as Array<any>).map(ApartmentImagesToJSON),
    roominess: ApartmentRoominessToJSON(value.roominess),
    balconiesCount: value.balconiesCount,
    loggiasCount: value.loggiasCount,
    combinedWcsCount: value.combinedWcsCount,
    separateWcsCount: value.separateWcsCount,
    floorNumber: value.floorNumber,
    fullArea: value.fullArea,
    livingArea: value.livingArea,
    kitchensArea: value.kitchensArea,
    balconiesAndLoggiasArea: value.balconiesAndLoggiasArea,
    bedroomsArea: value.bedroomsArea,
    bathroomsArea: value.bathroomsArea,
    wcsArea: value.wcsArea,
    hallwaysArea: value.hallwaysArea,
    priceRub: value.priceRub,
    buildingSeries: value.buildingSeries,
    buildingConstructionYear: value.buildingConstructionYear,
    buildingConstructionYearComment: value.buildingConstructionYearComment,
    buildingFloorCount: value.buildingFloorCount,
    buildingCeilingHeight: value.buildingCeilingHeight,
    buildingPassengerElevatorsCount: value.buildingPassengerElevatorsCount,
    buildingFreightElevatorsCount: value.buildingFreightElevatorsCount,
    isBuildingHasGarbageChute: value.isBuildingHasGarbageChute,
    buildingPorchsCount: value.buildingPorchsCount,
    buildingType: ApartmentReferenceToJSON(value.buildingType),
    buildingParkingType: ApartmentReferenceToJSON(value.buildingParkingType),
    buildingDeveloper: ApartmentReferenceToJSON(value.buildingDeveloper),
    housingComplex: ApartmentReferenceToJSON(value.housingComplex),
    housingComplexBuilding: ApartmentReferenceToJSON(value.housingComplexBuilding),
    saleTypes: (value.saleTypes as Array<any>).map(ApartmentReferenceToJSON),
    housingType: ApartmentReferenceToJSON(value.housingType),
    decorationType: ApartmentReferenceToJSON(value.decorationType),
    heatingType: ApartmentReferenceToJSON(value.heatingType),
    roomType: ApartmentReferenceToJSON(value.roomType),
    stoveType: ApartmentReferenceToJSON(value.stoveType),
    windowViewType: ApartmentReferenceToJSON(value.windowViewType),
    contactPhoneNumber: value.contactPhoneNumber,
    isRedevelopment: value.isRedevelopment,
    loanRate: value.loanRate,
    discountRate: value.discountRate,
    statusLabel: value.statusLabel,
  }
}
