/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry,
  ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryFromJSON,
  ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryFromJSONTyped,
  ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryToJSON,
  ApartmentsMapResponseV2ResponseBodyObjectManagerProperties,
  ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesFromJSON,
  ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesFromJSONTyped,
  ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures
 */
export interface ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures {
  /**
   *
   * @type {string}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures
   */
  type?: ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesTypeEnum
  /**
   *
   * @type {number}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures
   */
  id?: number
  /**
   *
   * @type {ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures
   */
  geometry?: ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry
  /**
   *
   * @type {ApartmentsMapResponseV2ResponseBodyObjectManagerProperties}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures
   */
  properties?: ApartmentsMapResponseV2ResponseBodyObjectManagerProperties
}

/**
 * @export
 * @enum {string}
 */
export enum ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesTypeEnum {
  Feature = 'Feature',
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesFromJSON(
  json: any,
): ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures {
  return ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesFromJSONTyped(json, false)
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures {
  if (json === undefined || json === null) {
    return json
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    id: !exists(json, 'id') ? undefined : json['id'],
    geometry: !exists(json, 'geometry')
      ? undefined
      : ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryFromJSON(json['geometry']),
    properties: !exists(json, 'properties')
      ? undefined
      : ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesFromJSON(json['properties']),
  }
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerFeaturesToJSON(
  value?: ApartmentsMapResponseV2ResponseBodyObjectManagerFeatures | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    type: value.type,
    id: value.id,
    geometry: ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryToJSON(value.geometry),
    properties: ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesToJSON(
      value.properties,
    ),
  }
}
