/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Описание полей в https://docs.google.com/spreadsheets/d/1YpR5cWan1DRIx0F1i1Th2v8yQ1OZLsrAnAWKVPUa4Y4/edit#gid=0
 * @export
 * @interface ApartmentAmoHistoryAmoHistory
 */
export interface ApartmentAmoHistoryAmoHistory {
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _673559?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _684643?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _780121?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  hirLcQku?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _764683?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _764685?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _5ueIEF5P?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  jsit07Wz?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _764691?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  tDz9B66r?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _764687?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _764689?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _771347?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  v7HBbI69?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  vAPlbzfg?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  bhkSH53F?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  ygtTtzFX?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  jtTOnZvX?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _1tW2TwPo?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  aoc2d5Lp?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _45rHJX7F?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  jVZ4UuLd?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  pUdSQBIg?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  yjGKPguD?: string | null
  /**
   *
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  l8s9cBSr?: string | null
  /**
   * Дата снятия обременения
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  _780231?: string | null
  /**
   * ДДУ / Договор долевого участия
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  dduLink?: string | null
  /**
   * ДУПТ ПБ / Договор уступки права требования ПИК-Брокер
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  duptPbLink?: string | null
  /**
   * АВЗ ПБ / Акт взаиморасчетов ПИК-Брокер
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  avzPbLink?: string | null
  /**
   * ПП ПБ / Платежное поручение ПИК-Брокер
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  ppLink?: string | null
  /**
   * Договор счета эскроу
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  escrowLink?: string | null
  /**
   * Платежное поручение о зачислении денежных средств на эскроу
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  ppOdsLink?: string | null
  /**
   * Справка о погашении кредита
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  creditLink?: string | null
  /**
   * Выписка из ЕГРН / Свидетельство о праве собственности клиента
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  egrnLink?: string | null
  /**
   * Правоустанавливающий документ
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  titleDocumentLink?: string | null
  /**
   * ЕГРН ПБ / Единый государственный реестр недвижимости ПИК-Брокер
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  egrnPbLink?: string | null
  /**
   * ДКП ПБ / Договор купли продажи ПИК-Брокер
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  dkpPbLink?: string | null
  /**
   * АПП ПБ / Акт приема-передачи ПИК-Брокер
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  appPbLink?: string | null
  /**
   * Чистая ВДК / Выписка из домовой книги
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  vdkLink?: string | null
  /**
   * Согласие супруга / нотариальное заявление об отсутствии брака/ брачный договор
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  agreementLink?: string | null
  /**
   * Юридическое заключение
   * @type {string}
   * @memberof ApartmentAmoHistoryAmoHistory
   */
  legalOpinion?: string | null
}

export function ApartmentAmoHistoryAmoHistoryFromJSON(json: any): ApartmentAmoHistoryAmoHistory {
  return ApartmentAmoHistoryAmoHistoryFromJSONTyped(json, false)
}

export function ApartmentAmoHistoryAmoHistoryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentAmoHistoryAmoHistory {
  if (json === undefined || json === null) {
    return json
  }
  return {
    _673559: !exists(json, '673559') ? undefined : json['673559'],
    _684643: !exists(json, '684643') ? undefined : json['684643'],
    _780121: !exists(json, '780121') ? undefined : json['780121'],
    hirLcQku: !exists(json, 'hirLcQku') ? undefined : json['hirLcQku'],
    _764683: !exists(json, '764683') ? undefined : json['764683'],
    _764685: !exists(json, '764685') ? undefined : json['764685'],
    _5ueIEF5P: !exists(json, '5UeIEF5P') ? undefined : json['5UeIEF5P'],
    jsit07Wz: !exists(json, 'Jsit07Wz') ? undefined : json['Jsit07Wz'],
    _764691: !exists(json, '764691') ? undefined : json['764691'],
    tDz9B66r: !exists(json, 'TDz9B66r') ? undefined : json['TDz9B66r'],
    _764687: !exists(json, '764687') ? undefined : json['764687'],
    _764689: !exists(json, '764689') ? undefined : json['764689'],
    _771347: !exists(json, '771347') ? undefined : json['771347'],
    v7HBbI69: !exists(json, 'V7HBbI69') ? undefined : json['V7HBbI69'],
    vAPlbzfg: !exists(json, 'VAPlbzfg') ? undefined : json['VAPlbzfg'],
    bhkSH53F: !exists(json, 'bhkSH53F') ? undefined : json['bhkSH53F'],
    ygtTtzFX: !exists(json, 'YgtTtzFX') ? undefined : json['YgtTtzFX'],
    jtTOnZvX: !exists(json, 'JtTOnZvX') ? undefined : json['JtTOnZvX'],
    _1tW2TwPo: !exists(json, '1TW2TwPo') ? undefined : json['1TW2TwPo'],
    aoc2d5Lp: !exists(json, 'Aoc2d5Lp') ? undefined : json['Aoc2d5Lp'],
    _45rHJX7F: !exists(json, '45rHJX7F') ? undefined : json['45rHJX7F'],
    jVZ4UuLd: !exists(json, 'JVZ4UuLd') ? undefined : json['JVZ4UuLd'],
    pUdSQBIg: !exists(json, 'pUdSQBIg') ? undefined : json['pUdSQBIg'],
    yjGKPguD: !exists(json, 'YjGKPguD') ? undefined : json['YjGKPguD'],
    l8s9cBSr: !exists(json, 'l8s9cBSr') ? undefined : json['l8s9cBSr'],
    _780231: !exists(json, '780231') ? undefined : json['780231'],
    dduLink: !exists(json, 'ddu_link') ? undefined : json['ddu_link'],
    duptPbLink: !exists(json, 'dupt_pb_link') ? undefined : json['dupt_pb_link'],
    avzPbLink: !exists(json, 'avz_pb_link') ? undefined : json['avz_pb_link'],
    ppLink: !exists(json, 'pp_link') ? undefined : json['pp_link'],
    escrowLink: !exists(json, 'escrow_link') ? undefined : json['escrow_link'],
    ppOdsLink: !exists(json, 'pp_ods_link') ? undefined : json['pp_ods_link'],
    creditLink: !exists(json, 'credit_link') ? undefined : json['credit_link'],
    egrnLink: !exists(json, 'egrn_link') ? undefined : json['egrn_link'],
    titleDocumentLink: !exists(json, 'title_document_link')
      ? undefined
      : json['title_document_link'],
    egrnPbLink: !exists(json, 'egrn_pb_link') ? undefined : json['egrn_pb_link'],
    dkpPbLink: !exists(json, 'dkp_pb_link') ? undefined : json['dkp_pb_link'],
    appPbLink: !exists(json, 'app_pb_link') ? undefined : json['app_pb_link'],
    vdkLink: !exists(json, 'vdk_link') ? undefined : json['vdk_link'],
    agreementLink: !exists(json, 'agreement_link') ? undefined : json['agreement_link'],
    legalOpinion: !exists(json, 'legal_opinion') ? undefined : json['legal_opinion'],
  }
}

export function ApartmentAmoHistoryAmoHistoryToJSON(
  value?: ApartmentAmoHistoryAmoHistory | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    '673559': value._673559,
    '684643': value._684643,
    '780121': value._780121,
    hirLcQku: value.hirLcQku,
    '764683': value._764683,
    '764685': value._764685,
    '5UeIEF5P': value._5ueIEF5P,
    Jsit07Wz: value.jsit07Wz,
    '764691': value._764691,
    TDz9B66r: value.tDz9B66r,
    '764687': value._764687,
    '764689': value._764689,
    '771347': value._771347,
    V7HBbI69: value.v7HBbI69,
    VAPlbzfg: value.vAPlbzfg,
    bhkSH53F: value.bhkSH53F,
    YgtTtzFX: value.ygtTtzFX,
    JtTOnZvX: value.jtTOnZvX,
    '1TW2TwPo': value._1tW2TwPo,
    Aoc2d5Lp: value.aoc2d5Lp,
    '45rHJX7F': value._45rHJX7F,
    JVZ4UuLd: value.jVZ4UuLd,
    pUdSQBIg: value.pUdSQBIg,
    YjGKPguD: value.yjGKPguD,
    l8s9cBSr: value.l8s9cBSr,
    '780231': value._780231,
    ddu_link: value.dduLink,
    dupt_pb_link: value.duptPbLink,
    avz_pb_link: value.avzPbLink,
    pp_link: value.ppLink,
    escrow_link: value.escrowLink,
    pp_ods_link: value.ppOdsLink,
    credit_link: value.creditLink,
    egrn_link: value.egrnLink,
    title_document_link: value.titleDocumentLink,
    egrn_pb_link: value.egrnPbLink,
    dkp_pb_link: value.dkpPbLink,
    app_pb_link: value.appPbLink,
    vdk_link: value.vdkLink,
    agreement_link: value.agreementLink,
    legal_opinion: value.legalOpinion,
  }
}
