/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPin
 */
export interface ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPin {
  /**
   *
   * @type {number}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPin
   */
  minPrice?: number
  /**
   *
   * @type {Array<number>}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPin
   */
  apartments?: Array<number>
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPinFromJSON(
  json: any,
): ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPin {
  return ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPinFromJSONTyped(json, false)
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPinFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPin {
  if (json === undefined || json === null) {
    return json
  }
  return {
    minPrice: !exists(json, 'minPrice') ? undefined : json['minPrice'],
    apartments: !exists(json, 'apartments') ? undefined : json['apartments'],
  }
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPinToJSON(
  value?: ApartmentsMapResponseV2ResponseBodyObjectManagerPropertiesPin | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    minPrice: value.minPrice,
    apartments: value.apartments,
  }
}
