/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry
 */
export interface ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry {
  /**
   *
   * @type {string}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry
   */
  type?: ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryTypeEnum
  /**
   *
   * @type {Array<number>}
   * @memberof ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry
   */
  coordinates?: Array<number>
}

/**
 * @export
 * @enum {string}
 */
export enum ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryTypeEnum {
  Point = 'Point',
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryFromJSON(
  json: any,
): ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry {
  return ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryFromJSONTyped(json, false)
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry {
  if (json === undefined || json === null) {
    return json
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    coordinates: !exists(json, 'coordinates') ? undefined : json['coordinates'],
  }
}

export function ApartmentsMapResponseV2ResponseBodyObjectManagerGeometryToJSON(
  value?: ApartmentsMapResponseV2ResponseBodyObjectManagerGeometry | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    type: value.type,
    coordinates: value.coordinates,
  }
}
