/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ApartmentVideos
 */
export interface ApartmentVideos {
  /**
   *
   * @type {string}
   * @memberof ApartmentVideos
   */
  source: string
  /**
   *
   * @type {string}
   * @memberof ApartmentVideos
   */
  id: string
}

export function ApartmentVideosFromJSON(json: any): ApartmentVideos {
  return ApartmentVideosFromJSONTyped(json, false)
}

export function ApartmentVideosFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentVideos {
  if (json === undefined || json === null) {
    return json
  }
  return {
    source: json['source'],
    id: json['id'],
  }
}

export function ApartmentVideosToJSON(value?: ApartmentVideos | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    source: value.source,
    id: value.id,
  }
}
