/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SortBy,
  SortByFromJSON,
  SortByFromJSONTyped,
  SortByToJSON,
  SortOrder,
  SortOrderFromJSON,
  SortOrderFromJSONTyped,
  SortOrderToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentsSorts
 */
export interface ApartmentsSorts {
  /**
   *
   * @type {number}
   * @memberof ApartmentsSorts
   */
  page?: number
  /**
   *
   * @type {SortBy}
   * @memberof ApartmentsSorts
   */
  sortBy?: SortBy
  /**
   *
   * @type {SortOrder}
   * @memberof ApartmentsSorts
   */
  sortOrder?: SortOrder
}

export function ApartmentsSortsFromJSON(json: any): ApartmentsSorts {
  return ApartmentsSortsFromJSONTyped(json, false)
}

export function ApartmentsSortsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsSorts {
  if (json === undefined || json === null) {
    return json
  }
  return {
    page: !exists(json, 'page') ? undefined : json['page'],
    sortBy: !exists(json, 'sortBy') ? undefined : SortByFromJSON(json['sortBy']),
    sortOrder: !exists(json, 'sortOrder') ? undefined : SortOrderFromJSON(json['sortOrder']),
  }
}

export function ApartmentsSortsToJSON(value?: ApartmentsSorts | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    page: value.page,
    sortBy: SortByToJSON(value.sortBy),
    sortOrder: SortOrderToJSON(value.sortOrder),
  }
}
