/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentsMapResponseV2ResponseBody,
  ApartmentsMapResponseV2ResponseBodyFromJSON,
  ApartmentsMapResponseV2ResponseBodyFromJSONTyped,
  ApartmentsMapResponseV2ResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface ApartmentsMapResponseV2Response
 */
export interface ApartmentsMapResponseV2Response {
  /**
   *
   * @type {ApartmentsMapResponseV2ResponseBody}
   * @memberof ApartmentsMapResponseV2Response
   */
  body: ApartmentsMapResponseV2ResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof ApartmentsMapResponseV2Response
   */
  errors: Array<object>
}

export function ApartmentsMapResponseV2ResponseFromJSON(
  json: any,
): ApartmentsMapResponseV2Response {
  return ApartmentsMapResponseV2ResponseFromJSONTyped(json, false)
}

export function ApartmentsMapResponseV2ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApartmentsMapResponseV2Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: ApartmentsMapResponseV2ResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function ApartmentsMapResponseV2ResponseToJSON(
  value?: ApartmentsMapResponseV2Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: ApartmentsMapResponseV2ResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
