/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface BatchRequestBatch
 */
export interface BatchRequestBatch {
  /**
   *
   * @type {string}
   * @memberof BatchRequestBatch
   */
  method: string
  /**
   *
   * @type {string}
   * @memberof BatchRequestBatch
   */
  path: string
  /**
   *
   * @type {object}
   * @memberof BatchRequestBatch
   */
  body?: object
  /**
   *
   * @type {object}
   * @memberof BatchRequestBatch
   */
  params?: object
}

export function BatchRequestBatchFromJSON(json: any): BatchRequestBatch {
  return BatchRequestBatchFromJSONTyped(json, false)
}

export function BatchRequestBatchFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BatchRequestBatch {
  if (json === undefined || json === null) {
    return json
  }
  return {
    method: json['method'],
    path: json['path'],
    body: !exists(json, 'body') ? undefined : json['body'],
    params: !exists(json, 'params') ? undefined : json['params'],
  }
}

export function BatchRequestBatchToJSON(value?: BatchRequestBatch | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    method: value.method,
    path: value.path,
    body: value.body,
    params: value.params,
  }
}
