/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface BatchResponseResponseBody
 */
export interface BatchResponseResponseBody {
  /**
   *
   * @type {Array<object>}
   * @memberof BatchResponseResponseBody
   */
  batch?: Array<object>
}

export function BatchResponseResponseBodyFromJSON(json: any): BatchResponseResponseBody {
  return BatchResponseResponseBodyFromJSONTyped(json, false)
}

export function BatchResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BatchResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    batch: !exists(json, 'batch') ? undefined : json['batch'],
  }
}

export function BatchResponseResponseBodyToJSON(value?: BatchResponseResponseBody | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    batch: value.batch,
  }
}
