/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  BatchRequestBatch,
  BatchRequestBatchFromJSON,
  BatchRequestBatchFromJSONTyped,
  BatchRequestBatchToJSON,
} from './'

/**
 *
 * @export
 * @interface BatchRequest
 */
export interface BatchRequest {
  /**
   *
   * @type {Array<BatchRequestBatch>}
   * @memberof BatchRequest
   */
  batch?: Array<BatchRequestBatch>
}

export function BatchRequestFromJSON(json: any): BatchRequest {
  return BatchRequestFromJSONTyped(json, false)
}

export function BatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    batch: !exists(json, 'batch')
      ? undefined
      : (json['batch'] as Array<any>).map(BatchRequestBatchFromJSON),
  }
}

export function BatchRequestToJSON(value?: BatchRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    batch:
      value.batch === undefined
        ? undefined
        : (value.batch as Array<any>).map(BatchRequestBatchToJSON),
  }
}
