/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  BoundingBoxResponseResponseBody,
  BoundingBoxResponseResponseBodyFromJSON,
  BoundingBoxResponseResponseBodyFromJSONTyped,
  BoundingBoxResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface BoundingBoxResponseResponse
 */
export interface BoundingBoxResponseResponse {
  /**
   *
   * @type {BoundingBoxResponseResponseBody}
   * @memberof BoundingBoxResponseResponse
   */
  body: BoundingBoxResponseResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof BoundingBoxResponseResponse
   */
  errors: Array<object>
}

export function BoundingBoxResponseResponseFromJSON(json: any): BoundingBoxResponseResponse {
  return BoundingBoxResponseResponseFromJSONTyped(json, false)
}

export function BoundingBoxResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BoundingBoxResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: BoundingBoxResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function BoundingBoxResponseResponseToJSON(
  value?: BoundingBoxResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: BoundingBoxResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
