/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Point, PointFromJSON, PointFromJSONTyped, PointToJSON } from './'

/**
 *
 * @export
 * @interface BoundingBoxResponseResponseBodyBoundingBox
 */
export interface BoundingBoxResponseResponseBodyBoundingBox {
  /**
   *
   * @type {Point}
   * @memberof BoundingBoxResponseResponseBodyBoundingBox
   */
  bottomLeft: Point
  /**
   *
   * @type {Point}
   * @memberof BoundingBoxResponseResponseBodyBoundingBox
   */
  bottomRight: Point
  /**
   *
   * @type {Point}
   * @memberof BoundingBoxResponseResponseBodyBoundingBox
   */
  topRight: Point
  /**
   *
   * @type {Point}
   * @memberof BoundingBoxResponseResponseBodyBoundingBox
   */
  topLeft: Point
  /**
   *
   * @type {number}
   * @memberof BoundingBoxResponseResponseBodyBoundingBox
   */
  distance: number
}

export function BoundingBoxResponseResponseBodyBoundingBoxFromJSON(
  json: any,
): BoundingBoxResponseResponseBodyBoundingBox {
  return BoundingBoxResponseResponseBodyBoundingBoxFromJSONTyped(json, false)
}

export function BoundingBoxResponseResponseBodyBoundingBoxFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BoundingBoxResponseResponseBodyBoundingBox {
  if (json === undefined || json === null) {
    return json
  }
  return {
    bottomLeft: PointFromJSON(json['bottomLeft']),
    bottomRight: PointFromJSON(json['bottomRight']),
    topRight: PointFromJSON(json['topRight']),
    topLeft: PointFromJSON(json['topLeft']),
    distance: json['distance'],
  }
}

export function BoundingBoxResponseResponseBodyBoundingBoxToJSON(
  value?: BoundingBoxResponseResponseBodyBoundingBox | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    bottomLeft: PointToJSON(value.bottomLeft),
    bottomRight: PointToJSON(value.bottomRight),
    topRight: PointToJSON(value.topRight),
    topLeft: PointToJSON(value.topLeft),
    distance: value.distance,
  }
}
