/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CatalogSelectOptions
 */
export interface CatalogSelectOptions {
  /**
   *
   * @type {string}
   * @memberof CatalogSelectOptions
   */
  value: string | null
  /**
   *
   * @type {string}
   * @memberof CatalogSelectOptions
   */
  caption: string
  /**
   *
   * @type {string}
   * @memberof CatalogSelectOptions
   */
  slug: string | null
}

export function CatalogSelectOptionsFromJSON(json: any): CatalogSelectOptions {
  return CatalogSelectOptionsFromJSONTyped(json, false)
}

export function CatalogSelectOptionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CatalogSelectOptions {
  if (json === undefined || json === null) {
    return json
  }
  return {
    value: json['value'],
    caption: json['caption'],
    slug: json['slug'],
  }
}

export function CatalogSelectOptionsToJSON(value?: CatalogSelectOptions | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    value: value.value,
    caption: value.caption,
    slug: value.slug,
  }
}
