/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CatalogSelectNewOptions
 */
export interface CatalogSelectNewOptions {
  /**
   *
   * @type {string}
   * @memberof CatalogSelectNewOptions
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof CatalogSelectNewOptions
   */
  name: string
}

export function CatalogSelectNewOptionsFromJSON(json: any): CatalogSelectNewOptions {
  return CatalogSelectNewOptionsFromJSONTyped(json, false)
}

export function CatalogSelectNewOptionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CatalogSelectNewOptions {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'],
  }
}

export function CatalogSelectNewOptionsToJSON(value?: CatalogSelectNewOptions | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    name: value.name,
  }
}
