/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ComplaintVerifyRequest
 */
export interface ComplaintVerifyRequest {
  /**
   *
   * @type {string}
   * @memberof ComplaintVerifyRequest
   */
  smsCode: string
}

export function ComplaintVerifyRequestFromJSON(json: any): ComplaintVerifyRequest {
  return ComplaintVerifyRequestFromJSONTyped(json, false)
}

export function ComplaintVerifyRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ComplaintVerifyRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    smsCode: json['sms_code'],
  }
}

export function ComplaintVerifyRequestToJSON(value?: ComplaintVerifyRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    sms_code: value.smsCode,
  }
}
