/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { City, CityFromJSON, CityFromJSONTyped, CityToJSON } from './'

/**
 * Сущности контактов
 * @export
 * @interface Contacts
 */
export interface Contacts {
  /**
   *
   * @type {number}
   * @memberof Contacts
   */
  initialCityId: number | null
  /**
   *
   * @type {Array<City>}
   * @memberof Contacts
   */
  cities: Array<City>
}

export function ContactsFromJSON(json: any): Contacts {
  return ContactsFromJSONTyped(json, false)
}

export function ContactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contacts {
  if (json === undefined || json === null) {
    return json
  }
  return {
    initialCityId: json['initial_city_id'],
    cities: (json['cities'] as Array<any>).map(CityFromJSON),
  }
}

export function ContactsToJSON(value?: Contacts | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    initial_city_id: value.initialCityId,
    cities: (value.cities as Array<any>).map(CityToJSON),
  }
}
