/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CoordsCheckerResponseResponse,
  CoordsCheckerResponseResponseFromJSON,
  CoordsCheckerResponseResponseFromJSONTyped,
  CoordsCheckerResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface CoordsCheckerResponse
 */
export interface CoordsCheckerResponse {
  /**
   *
   * @type {CoordsCheckerResponseResponse}
   * @memberof CoordsCheckerResponse
   */
  response: CoordsCheckerResponseResponse
}

export function CoordsCheckerResponseFromJSON(json: any): CoordsCheckerResponse {
  return CoordsCheckerResponseFromJSONTyped(json, false)
}

export function CoordsCheckerResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CoordsCheckerResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: CoordsCheckerResponseResponseFromJSON(json['response']),
  }
}

export function CoordsCheckerResponseToJSON(value?: CoordsCheckerResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: CoordsCheckerResponseResponseToJSON(value.response),
  }
}
