/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CoordsCheckerResponseResponseBody
 */
export interface CoordsCheckerResponseResponseBody {
  /**
   * Тип зоны выкупа:
   *     - *notBuyoutZone*: объект находится в зоне не подлежащей выкупу
   *     - *lowPriceZone*: объект находится в зоне пониженной оценки
   *     - *buyOutZone*: объект находится в зоне выкупа
   * @type {string}
   * @memberof CoordsCheckerResponseResponseBody
   */
  typeOfZone: CoordsCheckerResponseResponseBodyTypeOfZoneEnum
}

/**
 * @export
 * @enum {string}
 */
export enum CoordsCheckerResponseResponseBodyTypeOfZoneEnum {
  NotBuyoutZone = 'notBuyoutZone',
  LowPriceZone = 'lowPriceZone',
  BuyOutZone = 'buyOutZone',
}

export function CoordsCheckerResponseResponseBodyFromJSON(
  json: any,
): CoordsCheckerResponseResponseBody {
  return CoordsCheckerResponseResponseBodyFromJSONTyped(json, false)
}

export function CoordsCheckerResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CoordsCheckerResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    typeOfZone: json['typeOfZone'],
  }
}

export function CoordsCheckerResponseResponseBodyToJSON(
  value?: CoordsCheckerResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    typeOfZone: value.typeOfZone,
  }
}
