/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CountApartmentsResponseResponseBody,
  CountApartmentsResponseResponseBodyFromJSON,
  CountApartmentsResponseResponseBodyFromJSONTyped,
  CountApartmentsResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface CountApartmentsResponseResponse
 */
export interface CountApartmentsResponseResponse {
  /**
   *
   * @type {CountApartmentsResponseResponseBody}
   * @memberof CountApartmentsResponseResponse
   */
  body: CountApartmentsResponseResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof CountApartmentsResponseResponse
   */
  errors: Array<object>
}

export function CountApartmentsResponseResponseFromJSON(
  json: any,
): CountApartmentsResponseResponse {
  return CountApartmentsResponseResponseFromJSONTyped(json, false)
}

export function CountApartmentsResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountApartmentsResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: CountApartmentsResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function CountApartmentsResponseResponseToJSON(
  value?: CountApartmentsResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: CountApartmentsResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
