/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CountApartmentsResponseResponse,
  CountApartmentsResponseResponseFromJSON,
  CountApartmentsResponseResponseFromJSONTyped,
  CountApartmentsResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface CountApartmentsResponse
 */
export interface CountApartmentsResponse {
  /**
   *
   * @type {CountApartmentsResponseResponse}
   * @memberof CountApartmentsResponse
   */
  response: CountApartmentsResponseResponse
}

export function CountApartmentsResponseFromJSON(json: any): CountApartmentsResponse {
  return CountApartmentsResponseFromJSONTyped(json, false)
}

export function CountApartmentsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountApartmentsResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: CountApartmentsResponseResponseFromJSON(json['response']),
  }
}

export function CountApartmentsResponseToJSON(value?: CountApartmentsResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: CountApartmentsResponseResponseToJSON(value.response),
  }
}
