/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CountApartmentsResponseResponseBody
 */
export interface CountApartmentsResponseResponseBody {
  /**
   *
   * @type {number}
   * @memberof CountApartmentsResponseResponseBody
   */
  count: number
}

export function CountApartmentsResponseResponseBodyFromJSON(
  json: any,
): CountApartmentsResponseResponseBody {
  return CountApartmentsResponseResponseBodyFromJSONTyped(json, false)
}

export function CountApartmentsResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CountApartmentsResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    count: json['count'],
  }
}

export function CountApartmentsResponseResponseBodyToJSON(
  value?: CountApartmentsResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    count: value.count,
  }
}
