/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateLeadResponseResponseBody
 */
export interface CreateLeadResponseResponseBody {
  /**
   *
   * @type {number}
   * @memberof CreateLeadResponseResponseBody
   */
  id?: number
  /**
   *
   * @type {boolean}
   * @memberof CreateLeadResponseResponseBody
   */
  result: boolean
  /**
   *
   * @type {string}
   * @memberof CreateLeadResponseResponseBody
   */
  uuid: string
  /**
   *
   * @type {string}
   * @memberof CreateLeadResponseResponseBody
   */
  uuidMain: string
  /**
   *
   * @type {string}
   * @memberof CreateLeadResponseResponseBody
   */
  message: string
}

export function CreateLeadResponseResponseBodyFromJSON(
  json: any,
): CreateLeadResponseResponseBody {
  return CreateLeadResponseResponseBodyFromJSONTyped(json, false)
}

export function CreateLeadResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateLeadResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    result: json['result'],
    uuid: json['uuid'],
    uuidMain: json['uuid_main'],
    message: json['message'],
  }
}

export function CreateLeadResponseResponseBodyToJSON(
  value?: CreateLeadResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    result: value.result,
    uuid: value.uuid,
    uuid_main: value.uuidMain,
    message: value.message,
  }
}
