/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateComplaintResponseResponseBody
 */
export interface CreateComplaintResponseResponseBody {
  /**
   *
   * @type {number}
   * @memberof CreateComplaintResponseResponseBody
   */
  id: number
}

export function CreateComplaintResponseResponseBodyFromJSON(
  json: any,
): CreateComplaintResponseResponseBody {
  return CreateComplaintResponseResponseBodyFromJSONTyped(json, false)
}

export function CreateComplaintResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateComplaintResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
  }
}

export function CreateComplaintResponseResponseBodyToJSON(
  value?: CreateComplaintResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
  }
}
