/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Source, SourceFromJSON, SourceFromJSONTyped, SourceToJSON } from './'

/**
 *
 * @export
 * @interface CreateLeadRequest
 */
export interface CreateLeadRequest {
  /**
   *
   * @type {string}
   * @memberof CreateLeadRequest
   */
  formType: string
  /**
   *
   * @type {string}
   * @memberof CreateLeadRequest
   */
  phone: string
  /**
   *
   * @type {string}
   * @memberof CreateLeadRequest
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof CreateLeadRequest
   */
  apartmentId?: string | null
  /**
   *
   * @type {string}
   * @memberof CreateLeadRequest
   */
  gaId?: string | null
  /**
   *
   * @type {Source}
   * @memberof CreateLeadRequest
   */
  source: Source
  /**
   *
   * @type {boolean}
   * @memberof CreateLeadRequest
   */
  allowMarketing?: boolean
}

export function CreateLeadRequestFromJSON(json: any): CreateLeadRequest {
  return CreateLeadRequestFromJSONTyped(json, false)
}

export function CreateLeadRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateLeadRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    formType: json['form_type'],
    phone: json['phone'],
    name: !exists(json, 'name') ? undefined : json['name'],
    apartmentId: !exists(json, 'apartment_id') ? undefined : json['apartment_id'],
    gaId: !exists(json, 'ga_id') ? undefined : json['ga_id'],
    source: SourceFromJSON(json['source']),
    allowMarketing: !exists(json, 'allow_marketing') ? undefined : json['allow_marketing'],
  }
}

export function CreateLeadRequestToJSON(value?: CreateLeadRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    form_type: value.formType,
    phone: value.phone,
    name: value.name,
    apartment_id: value.apartmentId,
    ga_id: value.gaId,
    source: SourceToJSON(value.source),
    allow_marketing: value.allowMarketing,
  }
}
