/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CreateComplaintResponseResponse,
  CreateComplaintResponseResponseFromJSON,
  CreateComplaintResponseResponseFromJSONTyped,
  CreateComplaintResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface CreateComplaintResponse
 */
export interface CreateComplaintResponse {
  /**
   *
   * @type {CreateComplaintResponseResponse}
   * @memberof CreateComplaintResponse
   */
  response?: CreateComplaintResponseResponse
}

export function CreateComplaintResponseFromJSON(json: any): CreateComplaintResponse {
  return CreateComplaintResponseFromJSONTyped(json, false)
}

export function CreateComplaintResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateComplaintResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : CreateComplaintResponseResponseFromJSON(json['response']),
  }
}

export function CreateComplaintResponseToJSON(value?: CreateComplaintResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: CreateComplaintResponseResponseToJSON(value.response),
  }
}
