/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CreateLeadResponseResponseBody,
  CreateLeadResponseResponseBodyFromJSON,
  CreateLeadResponseResponseBodyFromJSONTyped,
  CreateLeadResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface CreateLeadResponseResponse
 */
export interface CreateLeadResponseResponse {
  /**
   *
   * @type {CreateLeadResponseResponseBody}
   * @memberof CreateLeadResponseResponse
   */
  body: CreateLeadResponseResponseBody | null
  /**
   *
   * @type {Array<object>}
   * @memberof CreateLeadResponseResponse
   */
  errors: Array<object>
}

export function CreateLeadResponseResponseFromJSON(json: any): CreateLeadResponseResponse {
  return CreateLeadResponseResponseFromJSONTyped(json, false)
}

export function CreateLeadResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateLeadResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: CreateLeadResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function CreateLeadResponseResponseToJSON(value?: CreateLeadResponseResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: CreateLeadResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
