/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CreateLeadResponseResponse,
  CreateLeadResponseResponseFromJSON,
  CreateLeadResponseResponseFromJSONTyped,
  CreateLeadResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface CreateLeadResponse
 */
export interface CreateLeadResponse {
  /**
   *
   * @type {CreateLeadResponseResponse}
   * @memberof CreateLeadResponse
   */
  response?: CreateLeadResponseResponse
}

export function CreateLeadResponseFromJSON(json: any): CreateLeadResponse {
  return CreateLeadResponseFromJSONTyped(json, false)
}

export function CreateLeadResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateLeadResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : CreateLeadResponseResponseFromJSON(json['response']),
  }
}

export function CreateLeadResponseToJSON(value?: CreateLeadResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: CreateLeadResponseResponseToJSON(value.response),
  }
}
