/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  EmptyBodyResponse,
  EmptyBodyResponseFromJSON,
  EmptyBodyResponseFromJSONTyped,
  EmptyBodyResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface EmptyBody
 */
export interface EmptyBody {
  /**
   *
   * @type {EmptyBodyResponse}
   * @memberof EmptyBody
   */
  response: EmptyBodyResponse
}

export function EmptyBodyFromJSON(json: any): EmptyBody {
  return EmptyBodyFromJSONTyped(json, false)
}

export function EmptyBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmptyBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: EmptyBodyResponseFromJSON(json['response']),
  }
}

export function EmptyBodyToJSON(value?: EmptyBody | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: EmptyBodyResponseToJSON(value.response),
  }
}
