/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ApartmentWithAmoHistory,
  ApartmentWithAmoHistoryFromJSON,
  ApartmentWithAmoHistoryFromJSONTyped,
  ApartmentWithAmoHistoryToJSON,
} from './'

/**
 *
 * @export
 * @interface GetApartmentResponseResponse
 */
export interface GetApartmentResponseResponse {
  /**
   *
   * @type {ApartmentWithAmoHistory}
   * @memberof GetApartmentResponseResponse
   */
  body: ApartmentWithAmoHistory
  /**
   *
   * @type {Array<object>}
   * @memberof GetApartmentResponseResponse
   */
  errors: Array<object>
}

export function GetApartmentResponseResponseFromJSON(json: any): GetApartmentResponseResponse {
  return GetApartmentResponseResponseFromJSONTyped(json, false)
}

export function GetApartmentResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetApartmentResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: ApartmentWithAmoHistoryFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetApartmentResponseResponseToJSON(
  value?: GetApartmentResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: ApartmentWithAmoHistoryToJSON(value.body),
    errors: value.errors,
  }
}
