/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetApartmentMetaResponseResponse,
  GetApartmentMetaResponseResponseFromJSON,
  GetApartmentMetaResponseResponseFromJSONTyped,
  GetApartmentMetaResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetApartmentMetaResponse
 */
export interface GetApartmentMetaResponse {
  /**
   *
   * @type {GetApartmentMetaResponseResponse}
   * @memberof GetApartmentMetaResponse
   */
  response: GetApartmentMetaResponseResponse
}

export function GetApartmentMetaResponseFromJSON(json: any): GetApartmentMetaResponse {
  return GetApartmentMetaResponseFromJSONTyped(json, false)
}

export function GetApartmentMetaResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetApartmentMetaResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: GetApartmentMetaResponseResponseFromJSON(json['response']),
  }
}

export function GetApartmentMetaResponseToJSON(value?: GetApartmentMetaResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetApartmentMetaResponseResponseToJSON(value.response),
  }
}
