/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetApartmentLoanResponseResponse,
  GetApartmentLoanResponseResponseFromJSON,
  GetApartmentLoanResponseResponseFromJSONTyped,
  GetApartmentLoanResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetApartmentLoanResponse
 */
export interface GetApartmentLoanResponse {
  /**
   *
   * @type {GetApartmentLoanResponseResponse}
   * @memberof GetApartmentLoanResponse
   */
  response: GetApartmentLoanResponseResponse
}

export function GetApartmentLoanResponseFromJSON(json: any): GetApartmentLoanResponse {
  return GetApartmentLoanResponseFromJSONTyped(json, false)
}

export function GetApartmentLoanResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetApartmentLoanResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: GetApartmentLoanResponseResponseFromJSON(json['response']),
  }
}

export function GetApartmentLoanResponseToJSON(value?: GetApartmentLoanResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetApartmentLoanResponseResponseToJSON(value.response),
  }
}
