/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetApartmentLoanResponseResponseBody
 */
export interface GetApartmentLoanResponseResponseBody {
  /**
   * id банка, который даёт rate
   * @type {string}
   * @memberof GetApartmentLoanResponseResponseBody
   */
  id: GetApartmentLoanResponseResponseBodyIdEnum
  /**
   * Сумма платежа по кредиту
   * @type {number}
   * @memberof GetApartmentLoanResponseResponseBody
   */
  payment: number
  /**
   * Текущая ставка
   * @type {number}
   * @memberof GetApartmentLoanResponseResponseBody
   */
  rate: number
  /**
   * id банка, который даёт nextRate
   * @type {string}
   * @memberof GetApartmentLoanResponseResponseBody
   */
  nextId: GetApartmentLoanResponseResponseBodyNextIdEnum
  /**
   * Ставка в следующем периоде
   * @type {number}
   * @memberof GetApartmentLoanResponseResponseBody
   */
  nextRate: number | null
  /**
   * Количество дней до слещующего периода
   * @type {number}
   * @memberof GetApartmentLoanResponseResponseBody
   */
  timeout: number | null
}

/**
 * @export
 * @enum {string}
 */
export enum GetApartmentLoanResponseResponseBodyIdEnum {
  Vtb = 'vtb',
  Alfa = 'alfa',
}
/**
 * @export
 * @enum {string}
 */
export enum GetApartmentLoanResponseResponseBodyNextIdEnum {
  Vtb = 'vtb',
  Alfa = 'alfa',
}

export function GetApartmentLoanResponseResponseBodyFromJSON(
  json: any,
): GetApartmentLoanResponseResponseBody {
  return GetApartmentLoanResponseResponseBodyFromJSONTyped(json, false)
}

export function GetApartmentLoanResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetApartmentLoanResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    payment: json['payment'],
    rate: json['rate'],
    nextId: json['nextId'],
    nextRate: json['nextRate'],
    timeout: json['timeout'],
  }
}

export function GetApartmentLoanResponseResponseBodyToJSON(
  value?: GetApartmentLoanResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    payment: value.payment,
    rate: value.rate,
    nextId: value.nextId,
    nextRate: value.nextRate,
    timeout: value.timeout,
  }
}
