/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetApartmentMetaResponseResponseBody,
  GetApartmentMetaResponseResponseBodyFromJSON,
  GetApartmentMetaResponseResponseBodyFromJSONTyped,
  GetApartmentMetaResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface GetApartmentMetaResponseResponse
 */
export interface GetApartmentMetaResponseResponse {
  /**
   *
   * @type {GetApartmentMetaResponseResponseBody}
   * @memberof GetApartmentMetaResponseResponse
   */
  body: GetApartmentMetaResponseResponseBody | null
  /**
   *
   * @type {Array<object>}
   * @memberof GetApartmentMetaResponseResponse
   */
  errors: Array<object>
}

export function GetApartmentMetaResponseResponseFromJSON(
  json: any,
): GetApartmentMetaResponseResponse {
  return GetApartmentMetaResponseResponseFromJSONTyped(json, false)
}

export function GetApartmentMetaResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetApartmentMetaResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: GetApartmentMetaResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetApartmentMetaResponseResponseToJSON(
  value?: GetApartmentMetaResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: GetApartmentMetaResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
