/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetApartmentMetaResponseResponseBody
 */
export interface GetApartmentMetaResponseResponseBody {
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  metaTitle: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  metaDescription: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  ogType: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  ogLocale: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  ogSiteName: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  ogTitle: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  ogDescription: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  ogUrl: string
  /**
   *
   * @type {string}
   * @memberof GetApartmentMetaResponseResponseBody
   */
  ogImageUrl: string | null
}

export function GetApartmentMetaResponseResponseBodyFromJSON(
  json: any,
): GetApartmentMetaResponseResponseBody {
  return GetApartmentMetaResponseResponseBodyFromJSONTyped(json, false)
}

export function GetApartmentMetaResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetApartmentMetaResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    metaTitle: json['meta_title'],
    metaDescription: json['meta_description'],
    ogType: json['og_type'],
    ogLocale: json['og_locale'],
    ogSiteName: json['og_site_name'],
    ogTitle: json['og_title'],
    ogDescription: json['og_description'],
    ogUrl: json['og_url'],
    ogImageUrl: json['og_image_url'],
  }
}

export function GetApartmentMetaResponseResponseBodyToJSON(
  value?: GetApartmentMetaResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    meta_title: value.metaTitle,
    meta_description: value.metaDescription,
    og_type: value.ogType,
    og_locale: value.ogLocale,
    og_site_name: value.ogSiteName,
    og_title: value.ogTitle,
    og_description: value.ogDescription,
    og_url: value.ogUrl,
    og_image_url: value.ogImageUrl,
  }
}
