/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Contacts, ContactsFromJSON, ContactsFromJSONTyped, ContactsToJSON } from './'

/**
 *
 * @export
 * @interface GetContactsResponseResponse
 */
export interface GetContactsResponseResponse {
  /**
   *
   * @type {Contacts}
   * @memberof GetContactsResponseResponse
   */
  body: Contacts
  /**
   *
   * @type {Array<object>}
   * @memberof GetContactsResponseResponse
   */
  errors: Array<object>
}

export function GetContactsResponseResponseFromJSON(json: any): GetContactsResponseResponse {
  return GetContactsResponseResponseFromJSONTyped(json, false)
}

export function GetContactsResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetContactsResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: ContactsFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetContactsResponseResponseToJSON(
  value?: GetContactsResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: ContactsToJSON(value.body),
    errors: value.errors,
  }
}
