/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetContactsResponseResponse,
  GetContactsResponseResponseFromJSON,
  GetContactsResponseResponseFromJSONTyped,
  GetContactsResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetContactsResponse
 */
export interface GetContactsResponse {
  /**
   *
   * @type {GetContactsResponseResponse}
   * @memberof GetContactsResponse
   */
  response: GetContactsResponseResponse
}

export function GetContactsResponseFromJSON(json: any): GetContactsResponse {
  return GetContactsResponseFromJSONTyped(json, false)
}

export function GetContactsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetContactsResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: GetContactsResponseResponseFromJSON(json['response']),
  }
}

export function GetContactsResponseToJSON(value?: GetContactsResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetContactsResponseResponseToJSON(value.response),
  }
}
