/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  CatalogSettings,
  CatalogSettingsFromJSON,
  CatalogSettingsFromJSONTyped,
  CatalogSettingsToJSON,
} from './'

/**
 *
 * @export
 * @interface GetCatalogSettingsResponseResponse
 */
export interface GetCatalogSettingsResponseResponse {
  /**
   *
   * @type {CatalogSettings}
   * @memberof GetCatalogSettingsResponseResponse
   */
  body: CatalogSettings
  /**
   *
   * @type {Array<object>}
   * @memberof GetCatalogSettingsResponseResponse
   */
  errors: Array<object>
}

export function GetCatalogSettingsResponseResponseFromJSON(
  json: any,
): GetCatalogSettingsResponseResponse {
  return GetCatalogSettingsResponseResponseFromJSONTyped(json, false)
}

export function GetCatalogSettingsResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCatalogSettingsResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: CatalogSettingsFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetCatalogSettingsResponseResponseToJSON(
  value?: GetCatalogSettingsResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: CatalogSettingsToJSON(value.body),
    errors: value.errors,
  }
}
