/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetCatalogSettingsResponseNewResponse,
  GetCatalogSettingsResponseNewResponseFromJSON,
  GetCatalogSettingsResponseNewResponseFromJSONTyped,
  GetCatalogSettingsResponseNewResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetCatalogSettingsResponseNew
 */
export interface GetCatalogSettingsResponseNew {
  /**
   *
   * @type {GetCatalogSettingsResponseNewResponse}
   * @memberof GetCatalogSettingsResponseNew
   */
  response: GetCatalogSettingsResponseNewResponse
}

export function GetCatalogSettingsResponseNewFromJSON(json: any): GetCatalogSettingsResponseNew {
  return GetCatalogSettingsResponseNewFromJSONTyped(json, false)
}

export function GetCatalogSettingsResponseNewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCatalogSettingsResponseNew {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: GetCatalogSettingsResponseNewResponseFromJSON(json['response']),
  }
}

export function GetCatalogSettingsResponseNewToJSON(
  value?: GetCatalogSettingsResponseNew | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetCatalogSettingsResponseNewResponseToJSON(value.response),
  }
}
