/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { MenuItem, MenuItemFromJSON, MenuItemFromJSONTyped, MenuItemToJSON } from './'

/**
 *
 * @export
 * @interface GetMenuResponseResponse
 */
export interface GetMenuResponseResponse {
  /**
   *
   * @type {{ [key: string]: Array<MenuItem>; }}
   * @memberof GetMenuResponseResponse
   */
  body: { [key: string]: Array<MenuItem> }
  /**
   *
   * @type {Array<object>}
   * @memberof GetMenuResponseResponse
   */
  errors: Array<object>
}

export function GetMenuResponseResponseFromJSON(json: any): GetMenuResponseResponse {
  return GetMenuResponseResponseFromJSONTyped(json, false)
}

export function GetMenuResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetMenuResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: mapValues(json['body'], (items) => items.map(MenuItemFromJSON)),
    errors: json['errors'],
  }
}

export function GetMenuResponseResponseToJSON(value?: GetMenuResponseResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: mapValues(value['body'], (items) => items.map(MenuItemToJSON)),
    errors: value.errors,
  }
}
