/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetPageResponseResponse,
  GetPageResponseResponseFromJSON,
  GetPageResponseResponseFromJSONTyped,
  GetPageResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetPageResponse
 */
export interface GetPageResponse {
  /**
   *
   * @type {GetPageResponseResponse}
   * @memberof GetPageResponse
   */
  response?: GetPageResponseResponse
}

export function GetPageResponseFromJSON(json: any): GetPageResponse {
  return GetPageResponseFromJSONTyped(json, false)
}

export function GetPageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPageResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : GetPageResponseResponseFromJSON(json['response']),
  }
}

export function GetPageResponseToJSON(value?: GetPageResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetPageResponseResponseToJSON(value.response),
  }
}
