/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  PageInfoShort,
  PageInfoShortFromJSON,
  PageInfoShortFromJSONTyped,
  PageInfoShortToJSON,
} from './'

/**
 *
 * @export
 * @interface GetPagesResponseResponseBody
 */
export interface GetPagesResponseResponseBody {
  /**
   *
   * @type {Array<PageInfoShort>}
   * @memberof GetPagesResponseResponseBody
   */
  pages?: Array<PageInfoShort>
}

export function GetPagesResponseResponseBodyFromJSON(json: any): GetPagesResponseResponseBody {
  return GetPagesResponseResponseBodyFromJSONTyped(json, false)
}

export function GetPagesResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPagesResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    pages: !exists(json, 'pages')
      ? undefined
      : (json['pages'] as Array<any>).map(PageInfoShortFromJSON),
  }
}

export function GetPagesResponseResponseBodyToJSON(
  value?: GetPagesResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    pages:
      value.pages === undefined
        ? undefined
        : (value.pages as Array<any>).map(PageInfoShortToJSON),
  }
}
