/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetProfileResponseResponseBody
 */
export interface GetProfileResponseResponseBody {
  /**
   *
   * @type {string}
   * @memberof GetProfileResponseResponseBody
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof GetProfileResponseResponseBody
   */
  email?: string | null
  /**
   *
   * @type {string}
   * @memberof GetProfileResponseResponseBody
   */
  phone?: string | null
  /**
   *
   * @type {number}
   * @memberof GetProfileResponseResponseBody
   */
  countActiveDeals?: number
}

export function GetProfileResponseResponseBodyFromJSON(
  json: any,
): GetProfileResponseResponseBody {
  return GetProfileResponseResponseBodyFromJSONTyped(json, false)
}

export function GetProfileResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetProfileResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    email: !exists(json, 'email') ? undefined : json['email'],
    phone: !exists(json, 'phone') ? undefined : json['phone'],
    countActiveDeals: !exists(json, 'countActiveDeals') ? undefined : json['countActiveDeals'],
  }
}

export function GetProfileResponseResponseBodyToJSON(
  value?: GetProfileResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    email: value.email,
    phone: value.phone,
    countActiveDeals: value.countActiveDeals,
  }
}
