/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetPagesResponseResponseBody,
  GetPagesResponseResponseBodyFromJSON,
  GetPagesResponseResponseBodyFromJSONTyped,
  GetPagesResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface GetPagesResponseResponse
 */
export interface GetPagesResponseResponse {
  /**
   *
   * @type {GetPagesResponseResponseBody}
   * @memberof GetPagesResponseResponse
   */
  body: GetPagesResponseResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof GetPagesResponseResponse
   */
  errors: Array<object>
}

export function GetPagesResponseResponseFromJSON(json: any): GetPagesResponseResponse {
  return GetPagesResponseResponseFromJSONTyped(json, false)
}

export function GetPagesResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPagesResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: GetPagesResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetPagesResponseResponseToJSON(value?: GetPagesResponseResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: GetPagesResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
