/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetProfileResponseResponseBody,
  GetProfileResponseResponseBodyFromJSON,
  GetProfileResponseResponseBodyFromJSONTyped,
  GetProfileResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface GetProfileResponseResponse
 */
export interface GetProfileResponseResponse {
  /**
   *
   * @type {GetProfileResponseResponseBody}
   * @memberof GetProfileResponseResponse
   */
  body: GetProfileResponseResponseBody | null
  /**
   *
   * @type {Array<object>}
   * @memberof GetProfileResponseResponse
   */
  errors: Array<object>
}

export function GetProfileResponseResponseFromJSON(json: any): GetProfileResponseResponse {
  return GetProfileResponseResponseFromJSONTyped(json, false)
}

export function GetProfileResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetProfileResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: GetProfileResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetProfileResponseResponseToJSON(value?: GetProfileResponseResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: GetProfileResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
