/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetPagesResponseResponse,
  GetPagesResponseResponseFromJSON,
  GetPagesResponseResponseFromJSONTyped,
  GetPagesResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetPagesResponse
 */
export interface GetPagesResponse {
  /**
   *
   * @type {GetPagesResponseResponse}
   * @memberof GetPagesResponse
   */
  response?: GetPagesResponseResponse
}

export function GetPagesResponseFromJSON(json: any): GetPagesResponse {
  return GetPagesResponseFromJSONTyped(json, false)
}

export function GetPagesResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPagesResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : GetPagesResponseResponseFromJSON(json['response']),
  }
}

export function GetPagesResponseToJSON(value?: GetPagesResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetPagesResponseResponseToJSON(value.response),
  }
}
