/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetUserpanelSettingsResponseResponseBody,
  GetUserpanelSettingsResponseResponseBodyFromJSON,
  GetUserpanelSettingsResponseResponseBodyFromJSONTyped,
  GetUserpanelSettingsResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface GetUserpanelSettingsResponseResponse
 */
export interface GetUserpanelSettingsResponseResponse {
  /**
   *
   * @type {GetUserpanelSettingsResponseResponseBody}
   * @memberof GetUserpanelSettingsResponseResponse
   */
  body: GetUserpanelSettingsResponseResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof GetUserpanelSettingsResponseResponse
   */
  errors: Array<object>
}

export function GetUserpanelSettingsResponseResponseFromJSON(
  json: any,
): GetUserpanelSettingsResponseResponse {
  return GetUserpanelSettingsResponseResponseFromJSONTyped(json, false)
}

export function GetUserpanelSettingsResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserpanelSettingsResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: GetUserpanelSettingsResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetUserpanelSettingsResponseResponseToJSON(
  value?: GetUserpanelSettingsResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: GetUserpanelSettingsResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
