/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { CatalogText, CatalogTextFromJSON, CatalogTextFromJSONTyped, CatalogTextToJSON } from './'

/**
 *
 * @export
 * @interface GetUserpanelSettingsResponseResponseBody
 */
export interface GetUserpanelSettingsResponseResponseBody {
  /**
   *
   * @type {CatalogText}
   * @memberof GetUserpanelSettingsResponseResponseBody
   */
  name: CatalogText
  /**
   *
   * @type {CatalogText}
   * @memberof GetUserpanelSettingsResponseResponseBody
   */
  phone: CatalogText
}

export function GetUserpanelSettingsResponseResponseBodyFromJSON(
  json: any,
): GetUserpanelSettingsResponseResponseBody {
  return GetUserpanelSettingsResponseResponseBodyFromJSONTyped(json, false)
}

export function GetUserpanelSettingsResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserpanelSettingsResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: CatalogTextFromJSON(json['name']),
    phone: CatalogTextFromJSON(json['phone']),
  }
}

export function GetUserpanelSettingsResponseResponseBodyToJSON(
  value?: GetUserpanelSettingsResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: CatalogTextToJSON(value.name),
    phone: CatalogTextToJSON(value.phone),
  }
}
