/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetUserpanelSettingsResponseResponse,
  GetUserpanelSettingsResponseResponseFromJSON,
  GetUserpanelSettingsResponseResponseFromJSONTyped,
  GetUserpanelSettingsResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetUserpanelSettingsResponse
 */
export interface GetUserpanelSettingsResponse {
  /**
   *
   * @type {GetUserpanelSettingsResponseResponse}
   * @memberof GetUserpanelSettingsResponse
   */
  response?: GetUserpanelSettingsResponseResponse
}

export function GetUserpanelSettingsResponseFromJSON(json: any): GetUserpanelSettingsResponse {
  return GetUserpanelSettingsResponseFromJSONTyped(json, false)
}

export function GetUserpanelSettingsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserpanelSettingsResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : GetUserpanelSettingsResponseResponseFromJSON(json['response']),
  }
}

export function GetUserpanelSettingsResponseToJSON(
  value?: GetUserpanelSettingsResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetUserpanelSettingsResponseResponseToJSON(value.response),
  }
}
