/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetWidgetsResponseResponseBody,
  GetWidgetsResponseResponseBodyFromJSON,
  GetWidgetsResponseResponseBodyFromJSONTyped,
  GetWidgetsResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface GetWidgetsResponseResponse
 */
export interface GetWidgetsResponseResponse {
  /**
   *
   * @type {GetWidgetsResponseResponseBody}
   * @memberof GetWidgetsResponseResponse
   */
  body: GetWidgetsResponseResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof GetWidgetsResponseResponse
   */
  errors: Array<object>
}

export function GetWidgetsResponseResponseFromJSON(json: any): GetWidgetsResponseResponse {
  return GetWidgetsResponseResponseFromJSONTyped(json, false)
}

export function GetWidgetsResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWidgetsResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: GetWidgetsResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function GetWidgetsResponseResponseToJSON(value?: GetWidgetsResponseResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: GetWidgetsResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
