/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Widget, WidgetFromJSON, WidgetFromJSONTyped, WidgetToJSON } from './'

/**
 *
 * @export
 * @interface GetWidgetsResponseResponseBody
 */
export interface GetWidgetsResponseResponseBody {
  /**
   *
   * @type {Array<Widget>}
   * @memberof GetWidgetsResponseResponseBody
   */
  widgets?: Array<Widget>
}

export function GetWidgetsResponseResponseBodyFromJSON(
  json: any,
): GetWidgetsResponseResponseBody {
  return GetWidgetsResponseResponseBodyFromJSONTyped(json, false)
}

export function GetWidgetsResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWidgetsResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    widgets: !exists(json, 'widgets')
      ? undefined
      : (json['widgets'] as Array<any>).map(WidgetFromJSON),
  }
}

export function GetWidgetsResponseResponseBodyToJSON(
  value?: GetWidgetsResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    widgets:
      value.widgets === undefined ? undefined : (value.widgets as Array<any>).map(WidgetToJSON),
  }
}
