/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  GetWidgetsResponseResponse,
  GetWidgetsResponseResponseFromJSON,
  GetWidgetsResponseResponseFromJSONTyped,
  GetWidgetsResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface GetWidgetsResponse
 */
export interface GetWidgetsResponse {
  /**
   *
   * @type {GetWidgetsResponseResponse}
   * @memberof GetWidgetsResponse
   */
  response?: GetWidgetsResponseResponse
}

export function GetWidgetsResponseFromJSON(json: any): GetWidgetsResponse {
  return GetWidgetsResponseFromJSONTyped(json, false)
}

export function GetWidgetsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWidgetsResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : GetWidgetsResponseResponseFromJSON(json['response']),
  }
}

export function GetWidgetsResponseToJSON(value?: GetWidgetsResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: GetWidgetsResponseResponseToJSON(value.response),
  }
}
