/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InfrastructureResponseResponseBodyInfrastructure
 */
export interface InfrastructureResponseResponseBodyInfrastructure {
  /**
   *
   * @type {string}
   * @memberof InfrastructureResponseResponseBodyInfrastructure
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof InfrastructureResponseResponseBodyInfrastructure
   */
  query: string
  /**
   *
   * @type {string}
   * @memberof InfrastructureResponseResponseBodyInfrastructure
   */
  slug: string
}

export function InfrastructureResponseResponseBodyInfrastructureFromJSON(
  json: any,
): InfrastructureResponseResponseBodyInfrastructure {
  return InfrastructureResponseResponseBodyInfrastructureFromJSONTyped(json, false)
}

export function InfrastructureResponseResponseBodyInfrastructureFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InfrastructureResponseResponseBodyInfrastructure {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: json['name'],
    query: json['query'],
    slug: json['slug'],
  }
}

export function InfrastructureResponseResponseBodyInfrastructureToJSON(
  value?: InfrastructureResponseResponseBodyInfrastructure | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    query: value.query,
    slug: value.slug,
  }
}
