/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  InfrastructureResponseResponseBody,
  InfrastructureResponseResponseBodyFromJSON,
  InfrastructureResponseResponseBodyFromJSONTyped,
  InfrastructureResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface InfrastructureResponseResponse
 */
export interface InfrastructureResponseResponse {
  /**
   *
   * @type {InfrastructureResponseResponseBody}
   * @memberof InfrastructureResponseResponse
   */
  body: InfrastructureResponseResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof InfrastructureResponseResponse
   */
  errors: Array<object>
}

export function InfrastructureResponseResponseFromJSON(
  json: any,
): InfrastructureResponseResponse {
  return InfrastructureResponseResponseFromJSONTyped(json, false)
}

export function InfrastructureResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InfrastructureResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: InfrastructureResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function InfrastructureResponseResponseToJSON(
  value?: InfrastructureResponseResponse | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: InfrastructureResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
