/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  InfrastructureResponseResponseBodyInfrastructure,
  InfrastructureResponseResponseBodyInfrastructureFromJSON,
  InfrastructureResponseResponseBodyInfrastructureFromJSONTyped,
  InfrastructureResponseResponseBodyInfrastructureToJSON,
} from './'

/**
 *
 * @export
 * @interface InfrastructureResponseResponseBody
 */
export interface InfrastructureResponseResponseBody {
  /**
   *
   * @type {Array<InfrastructureResponseResponseBodyInfrastructure>}
   * @memberof InfrastructureResponseResponseBody
   */
  infrastructure: Array<InfrastructureResponseResponseBodyInfrastructure>
}

export function InfrastructureResponseResponseBodyFromJSON(
  json: any,
): InfrastructureResponseResponseBody {
  return InfrastructureResponseResponseBodyFromJSONTyped(json, false)
}

export function InfrastructureResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InfrastructureResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    infrastructure: (json['infrastructure'] as Array<any>).map(
      InfrastructureResponseResponseBodyInfrastructureFromJSON,
    ),
  }
}

export function InfrastructureResponseResponseBodyToJSON(
  value?: InfrastructureResponseResponseBody | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    infrastructure: (value.infrastructure as Array<any>).map(
      InfrastructureResponseResponseBodyInfrastructureToJSON,
    ),
  }
}
