/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  InfrastructureResponseResponse,
  InfrastructureResponseResponseFromJSON,
  InfrastructureResponseResponseFromJSONTyped,
  InfrastructureResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface InfrastructureResponse
 */
export interface InfrastructureResponse {
  /**
   *
   * @type {InfrastructureResponseResponse}
   * @memberof InfrastructureResponse
   */
  response?: InfrastructureResponseResponse
}

export function InfrastructureResponseFromJSON(json: any): InfrastructureResponse {
  return InfrastructureResponseFromJSONTyped(json, false)
}

export function InfrastructureResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InfrastructureResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : InfrastructureResponseResponseFromJSON(json['response']),
  }
}

export function InfrastructureResponseToJSON(value?: InfrastructureResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: InfrastructureResponseResponseToJSON(value.response),
  }
}
