/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  LogInResponseResponseBody,
  LogInResponseResponseBodyFromJSON,
  LogInResponseResponseBodyFromJSONTyped,
  LogInResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface LogInResponseResponse
 */
export interface LogInResponseResponse {
  /**
   *
   * @type {LogInResponseResponseBody}
   * @memberof LogInResponseResponse
   */
  body: LogInResponseResponseBody | null
  /**
   *
   * @type {Array<object>}
   * @memberof LogInResponseResponse
   */
  errors: Array<object>
}

export function LogInResponseResponseFromJSON(json: any): LogInResponseResponse {
  return LogInResponseResponseFromJSONTyped(json, false)
}

export function LogInResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LogInResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: LogInResponseResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function LogInResponseResponseToJSON(value?: LogInResponseResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: LogInResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
