/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  LogInResponseResponse,
  LogInResponseResponseFromJSON,
  LogInResponseResponseFromJSONTyped,
  LogInResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface LogInResponse
 */
export interface LogInResponse {
  /**
   *
   * @type {LogInResponseResponse}
   * @memberof LogInResponse
   */
  response?: LogInResponseResponse
}

export function LogInResponseFromJSON(json: any): LogInResponse {
  return LogInResponseFromJSONTyped(json, false)
}

export function LogInResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LogInResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : LogInResponseResponseFromJSON(json['response']),
  }
}

export function LogInResponseToJSON(value?: LogInResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: LogInResponseResponseToJSON(value.response),
  }
}
