/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface LogInResponseResponseBody
 */
export interface LogInResponseResponseBody {
  /**
   *
   * @type {boolean}
   * @memberof LogInResponseResponseBody
   */
  status: boolean
  /**
   *
   * @type {string}
   * @memberof LogInResponseResponseBody
   */
  token?: string
  /**
   *
   * @type {string}
   * @memberof LogInResponseResponseBody
   */
  refreshToken?: string
  /**
   *
   * @type {number}
   * @memberof LogInResponseResponseBody
   */
  userId?: number
}

export function LogInResponseResponseBodyFromJSON(json: any): LogInResponseResponseBody {
  return LogInResponseResponseBodyFromJSONTyped(json, false)
}

export function LogInResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LogInResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    status: json['status'],
    token: !exists(json, 'token') ? undefined : json['token'],
    refreshToken: !exists(json, 'refreshToken') ? undefined : json['refreshToken'],
    userId: !exists(json, 'user_id') ? undefined : json['user_id'],
  }
}

export function LogInResponseResponseBodyToJSON(value?: LogInResponseResponseBody | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    status: value.status,
    token: value.token,
    refreshToken: value.refreshToken,
    user_id: value.userId,
  }
}
