/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface MenuItemAttr
 */
export interface MenuItemAttr {
  /**
   *
   * @type {string}
   * @memberof MenuItemAttr
   */
  rel?: string | null
  /**
   *
   * @type {string}
   * @memberof MenuItemAttr
   */
  target?: string | null
}

export function MenuItemAttrFromJSON(json: any): MenuItemAttr {
  return MenuItemAttrFromJSONTyped(json, false)
}

export function MenuItemAttrFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItemAttr {
  if (json === undefined || json === null) {
    return json
  }
  return {
    rel: !exists(json, 'rel') ? undefined : json['rel'],
    target: !exists(json, 'target') ? undefined : json['target'],
  }
}

export function MenuItemAttrToJSON(value?: MenuItemAttr | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    rel: value.rel,
    target: value.target,
  }
}
