/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  MenuItemAttr,
  MenuItemAttrFromJSON,
  MenuItemAttrFromJSONTyped,
  MenuItemAttrToJSON,
  MenuItemBadge,
  MenuItemBadgeFromJSON,
  MenuItemBadgeFromJSONTyped,
  MenuItemBadgeToJSON,
  MenuSubItem,
  MenuSubItemFromJSON,
  MenuSubItemFromJSONTyped,
  MenuSubItemToJSON,
} from './'

/**
 *
 * @export
 * @interface MenuItem
 */
export interface MenuItem {
  /**
   *
   * @type {MenuItemAttr}
   * @memberof MenuItem
   */
  attr: MenuItemAttr | null
  /**
   *
   * @type {string}
   * @memberof MenuItem
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof MenuItem
   */
  subtitle: string | null
  /**
   *
   * @type {string}
   * @memberof MenuItem
   */
  description: string | null
  /**
   *
   * @type {string}
   * @memberof MenuItem
   */
  slug: string
  /**
   *
   * @type {string}
   * @memberof MenuItem
   */
  background: string | null
  /**
   *
   * @type {string}
   * @memberof MenuItem
   */
  foreground: string | null
  /**
   *
   * @type {string}
   * @memberof MenuItem
   */
  href: string
  /**
   *
   * @type {MenuItemBadge}
   * @memberof MenuItem
   */
  suffix: MenuItemBadge | null
  /**
   *
   * @type {MenuItemBadge}
   * @memberof MenuItem
   */
  prefix: MenuItemBadge | null
  /**
   *
   * @type {object}
   * @memberof MenuItem
   */
  images: object | null
  /**
   *
   * @type {Array<MenuSubItem>}
   * @memberof MenuItem
   */
  items: Array<MenuSubItem>
}

export function MenuItemFromJSON(json: any): MenuItem {
  return MenuItemFromJSONTyped(json, false)
}

export function MenuItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MenuItem {
  if (json === undefined || json === null) {
    return json
  }
  return {
    attr: MenuItemAttrFromJSON(json['attr']),
    title: json['title'],
    subtitle: json['subtitle'],
    description: json['description'],
    slug: json['slug'],
    background: json['background'],
    foreground: json['foreground'],
    href: json['href'],
    suffix: MenuItemBadgeFromJSON(json['suffix']),
    prefix: MenuItemBadgeFromJSON(json['prefix']),
    images: json['images'],
    items: (json['items'] as Array<any>).map(MenuSubItemFromJSON),
  }
}

export function MenuItemToJSON(value?: MenuItem | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    attr: MenuItemAttrToJSON(value.attr),
    title: value.title,
    subtitle: value.subtitle,
    description: value.description,
    slug: value.slug,
    background: value.background,
    foreground: value.foreground,
    href: value.href,
    suffix: MenuItemBadgeToJSON(value.suffix),
    prefix: MenuItemBadgeToJSON(value.prefix),
    images: value.images,
    items: (value.items as Array<any>).map(MenuSubItemToJSON),
  }
}
