/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface MenuItemBadge
 */
export interface MenuItemBadge {
  /**
   *
   * @type {string}
   * @memberof MenuItemBadge
   */
  text?: string
  /**
   *
   * @type {string}
   * @memberof MenuItemBadge
   */
  background?: string | null
  /**
   *
   * @type {string}
   * @memberof MenuItemBadge
   */
  color?: string | null
}

export function MenuItemBadgeFromJSON(json: any): MenuItemBadge {
  return MenuItemBadgeFromJSONTyped(json, false)
}

export function MenuItemBadgeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MenuItemBadge {
  if (json === undefined || json === null) {
    return json
  }
  return {
    text: !exists(json, 'text') ? undefined : json['text'],
    background: !exists(json, 'background') ? undefined : json['background'],
    color: !exists(json, 'color') ? undefined : json['color'],
  }
}

export function MenuItemBadgeToJSON(value?: MenuItemBadge | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    text: value.text,
    background: value.background,
    color: value.color,
  }
}
