/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PageInfo
 */
export interface PageInfo {
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  alias: string
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  slug: string
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  metaTitle: string
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  metaDescription: string
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  ogTitle: string
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  ogDescription: string
  /**
   *
   * @type {string}
   * @memberof PageInfo
   */
  displayName: string
}

export function PageInfoFromJSON(json: any): PageInfo {
  return PageInfoFromJSONTyped(json, false)
}

export function PageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInfo {
  if (json === undefined || json === null) {
    return json
  }
  return {
    alias: json['alias'],
    slug: json['slug'],
    metaTitle: json['meta_title'],
    metaDescription: json['meta_description'],
    ogTitle: json['og_title'],
    ogDescription: json['og_description'],
    displayName: json['display_name'],
  }
}

export function PageInfoToJSON(value?: PageInfo | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    alias: value.alias,
    slug: value.slug,
    meta_title: value.metaTitle,
    meta_description: value.metaDescription,
    og_title: value.ogTitle,
    og_description: value.ogDescription,
    display_name: value.displayName,
  }
}
