/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PageInfoShort
 */
export interface PageInfoShort {
  /**
   *
   * @type {boolean}
   * @memberof PageInfoShort
   */
  main: boolean
  /**
   *
   * @type {boolean}
   * @memberof PageInfoShort
   */
  active: boolean
  /**
   *
   * @type {string}
   * @memberof PageInfoShort
   */
  alias: string
  /**
   *
   * @type {string}
   * @memberof PageInfoShort
   */
  slug: string
  /**
   *
   * @type {string}
   * @memberof PageInfoShort
   */
  metaTitle: string
  /**
   *
   * @type {string}
   * @memberof PageInfoShort
   */
  metaDescription: string
  /**
   *
   * @type {string}
   * @memberof PageInfoShort
   */
  ogTitle: string
  /**
   *
   * @type {string}
   * @memberof PageInfoShort
   */
  ogDescription: string
  /**
   *
   * @type {string}
   * @memberof PageInfoShort
   */
  displayName: string
}

export function PageInfoShortFromJSON(json: any): PageInfoShort {
  return PageInfoShortFromJSONTyped(json, false)
}

export function PageInfoShortFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PageInfoShort {
  if (json === undefined || json === null) {
    return json
  }
  return {
    main: json['main'],
    active: json['active'],
    alias: json['alias'],
    slug: json['slug'],
    metaTitle: json['meta_title'],
    metaDescription: json['meta_description'],
    ogTitle: json['og_title'],
    ogDescription: json['og_description'],
    displayName: json['display_name'],
  }
}

export function PageInfoShortToJSON(value?: PageInfoShort | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    main: value.main,
    active: value.active,
    alias: value.alias,
    slug: value.slug,
    meta_title: value.metaTitle,
    meta_description: value.metaDescription,
    og_title: value.ogTitle,
    og_description: value.ogDescription,
    display_name: value.displayName,
  }
}
