/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Point
 */
export interface Point {
  /**
   *
   * @type {number}
   * @memberof Point
   */
  longitude: number
  /**
   *
   * @type {number}
   * @memberof Point
   */
  latitude: number
}

export function PointFromJSON(json: any): Point {
  return PointFromJSONTyped(json, false)
}

export function PointFromJSONTyped(json: any, ignoreDiscriminator: boolean): Point {
  if (json === undefined || json === null) {
    return json
  }
  return {
    longitude: json['longitude'],
    latitude: json['latitude'],
  }
}

export function PointToJSON(value?: Point | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    longitude: value.longitude,
    latitude: value.latitude,
  }
}
