/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SearchApartmentsResponseV1Response,
  SearchApartmentsResponseV1ResponseFromJSON,
  SearchApartmentsResponseV1ResponseFromJSONTyped,
  SearchApartmentsResponseV1ResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface SearchApartmentsResponseV1
 */
export interface SearchApartmentsResponseV1 {
  /**
   *
   * @type {SearchApartmentsResponseV1Response}
   * @memberof SearchApartmentsResponseV1
   */
  response: SearchApartmentsResponseV1Response
}

export function SearchApartmentsResponseV1FromJSON(json: any): SearchApartmentsResponseV1 {
  return SearchApartmentsResponseV1FromJSONTyped(json, false)
}

export function SearchApartmentsResponseV1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SearchApartmentsResponseV1 {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: SearchApartmentsResponseV1ResponseFromJSON(json['response']),
  }
}

export function SearchApartmentsResponseV1ToJSON(value?: SearchApartmentsResponseV1 | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: SearchApartmentsResponseV1ResponseToJSON(value.response),
  }
}
