/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SearchApartmentsResponseV1ResponseBody,
  SearchApartmentsResponseV1ResponseBodyFromJSON,
  SearchApartmentsResponseV1ResponseBodyFromJSONTyped,
  SearchApartmentsResponseV1ResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface SearchApartmentsResponseV1Response
 */
export interface SearchApartmentsResponseV1Response {
  /**
   *
   * @type {SearchApartmentsResponseV1ResponseBody}
   * @memberof SearchApartmentsResponseV1Response
   */
  body: SearchApartmentsResponseV1ResponseBody
  /**
   *
   * @type {Array<object>}
   * @memberof SearchApartmentsResponseV1Response
   */
  errors: Array<object>
}

export function SearchApartmentsResponseV1ResponseFromJSON(
  json: any,
): SearchApartmentsResponseV1Response {
  return SearchApartmentsResponseV1ResponseFromJSONTyped(json, false)
}

export function SearchApartmentsResponseV1ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SearchApartmentsResponseV1Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: SearchApartmentsResponseV1ResponseBodyFromJSON(json['body']),
    errors: json['errors'],
  }
}

export function SearchApartmentsResponseV1ResponseToJSON(
  value?: SearchApartmentsResponseV1Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: SearchApartmentsResponseV1ResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
