/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SignUpResponseResponseBody
 */
export interface SignUpResponseResponseBody {
  /**
   *
   * @type {boolean}
   * @memberof SignUpResponseResponseBody
   */
  status: boolean
}

export function SignUpResponseResponseBodyFromJSON(json: any): SignUpResponseResponseBody {
  return SignUpResponseResponseBodyFromJSONTyped(json, false)
}

export function SignUpResponseResponseBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignUpResponseResponseBody {
  if (json === undefined || json === null) {
    return json
  }
  return {
    status: json['status'],
  }
}

export function SignUpResponseResponseBodyToJSON(value?: SignUpResponseResponseBody | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    status: value.status,
  }
}
