/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SignUpResponseResponseBody,
  SignUpResponseResponseBodyFromJSON,
  SignUpResponseResponseBodyFromJSONTyped,
  SignUpResponseResponseBodyToJSON,
} from './'

/**
 *
 * @export
 * @interface SignUpResponseResponse
 */
export interface SignUpResponseResponse {
  /**
   *
   * @type {SignUpResponseResponseBody}
   * @memberof SignUpResponseResponse
   */
  body?: SignUpResponseResponseBody | null
  /**
   *
   * @type {Array<object>}
   * @memberof SignUpResponseResponse
   */
  errors?: Array<object>
}

export function SignUpResponseResponseFromJSON(json: any): SignUpResponseResponse {
  return SignUpResponseResponseFromJSONTyped(json, false)
}

export function SignUpResponseResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignUpResponseResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    body: !exists(json, 'body') ? undefined : SignUpResponseResponseBodyFromJSON(json['body']),
    errors: !exists(json, 'errors') ? undefined : json['errors'],
  }
}

export function SignUpResponseResponseToJSON(value?: SignUpResponseResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    body: SignUpResponseResponseBodyToJSON(value.body),
    errors: value.errors,
  }
}
