/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SignUpResponseResponse,
  SignUpResponseResponseFromJSON,
  SignUpResponseResponseFromJSONTyped,
  SignUpResponseResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface SignUpResponse
 */
export interface SignUpResponse {
  /**
   *
   * @type {SignUpResponseResponse}
   * @memberof SignUpResponse
   */
  response?: SignUpResponseResponse
}

export function SignUpResponseFromJSON(json: any): SignUpResponse {
  return SignUpResponseFromJSONTyped(json, false)
}

export function SignUpResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignUpResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response')
      ? undefined
      : SignUpResponseResponseFromJSON(json['response']),
  }
}

export function SignUpResponseToJSON(value?: SignUpResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: SignUpResponseResponseToJSON(value.response),
  }
}
