/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum SortBy {
  CreatedAt = 'createdAt',
  PriceRub = 'priceRub',
  FullArea = 'fullArea',
}

export function SortByFromJSON(json: any): SortBy {
  return SortByFromJSONTyped(json, false)
}

export function SortByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortBy {
  return json as SortBy
}

export function SortByToJSON(value?: SortBy | null): any {
  return value as any
}
