/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Сайт-источник запроса
 * @export
 * @enum {string}
 */
export enum Source {
  KvartaRu = 'kvarta.ru',
  PikBrokerRu = 'pik-broker.ru',
}

export function SourceFromJSON(json: any): Source {
  return SourceFromJSONTyped(json, false)
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
  return json as Source
}

export function SourceToJSON(value?: Source | null): any {
  return value as any
}
