/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { SubwayLine, SubwayLineFromJSON, SubwayLineFromJSONTyped, SubwayLineToJSON } from './'

/**
 *
 * @export
 * @interface SubwayStation
 */
export interface SubwayStation {
  /**
   *
   * @type {string}
   * @memberof SubwayStation
   */
  uuid: string
  /**
   *
   * @type {string}
   * @memberof SubwayStation
   */
  displayName: string
  /**
   *
   * @type {SubwayLine}
   * @memberof SubwayStation
   */
  subwayLine: SubwayLine
}

export function SubwayStationFromJSON(json: any): SubwayStation {
  return SubwayStationFromJSONTyped(json, false)
}

export function SubwayStationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubwayStation {
  if (json === undefined || json === null) {
    return json
  }
  return {
    uuid: json['uuid'],
    displayName: json['displayName'],
    subwayLine: SubwayLineFromJSON(json['subwayLine']),
  }
}

export function SubwayStationToJSON(value?: SubwayStation | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    uuid: value.uuid,
    displayName: value.displayName,
    subwayLine: SubwayLineToJSON(value.subwayLine),
  }
}
