/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { Source, SourceFromJSON, SourceFromJSONTyped, SourceToJSON } from './'

/**
 *
 * @export
 * @interface UserpanelSignInRequest
 */
export interface UserpanelSignInRequest {
  /**
   *
   * @type {string}
   * @memberof UserpanelSignInRequest
   */
  phone: string
  /**
   *
   * @type {string}
   * @memberof UserpanelSignInRequest
   */
  gaId?: string | null
  /**
   *
   * @type {string}
   * @memberof UserpanelSignInRequest
   */
  recaptchaToken: string | null
  /**
   *
   * @type {Source}
   * @memberof UserpanelSignInRequest
   */
  source: Source
}

export function UserpanelSignInRequestFromJSON(json: any): UserpanelSignInRequest {
  return UserpanelSignInRequestFromJSONTyped(json, false)
}

export function UserpanelSignInRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserpanelSignInRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    phone: json['phone'],
    gaId: !exists(json, 'ga_id') ? undefined : json['ga_id'],
    recaptchaToken: json['recaptchaToken'],
    source: SourceFromJSON(json['source']),
  }
}

export function UserpanelSignInRequestToJSON(value?: UserpanelSignInRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    phone: value.phone,
    ga_id: value.gaId,
    recaptchaToken: value.recaptchaToken,
    source: SourceToJSON(value.source),
  }
}
