/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ValidationString
 */
export interface ValidationString {
  /**
   *
   * @type {string}
   * @memberof ValidationString
   */
  value: string
  /**
   *
   * @type {string}
   * @memberof ValidationString
   */
  message: string
}

export function ValidationStringFromJSON(json: any): ValidationString {
  return ValidationStringFromJSONTyped(json, false)
}

export function ValidationStringFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ValidationString {
  if (json === undefined || json === null) {
    return json
  }
  return {
    value: json['value'],
    message: json['message'],
  }
}

export function ValidationStringToJSON(value?: ValidationString | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    value: value.value,
    message: value.message,
  }
}
