/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  ValidationNumber,
  ValidationString,
  ValidationNumberFromJSONTyped,
  ValidationNumberToJSON,
  ValidationStringFromJSONTyped,
  ValidationStringToJSON,
} from './'

/**
 * @type ValidationStringOrNumber
 *
 * @export
 */
export type ValidationStringOrNumber = ValidationNumber | ValidationString

export function ValidationStringOrNumberFromJSON(json: any): ValidationStringOrNumber {
  return ValidationStringOrNumberFromJSONTyped(json, false)
}

export function ValidationStringOrNumberFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ValidationStringOrNumber {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...ValidationNumberFromJSONTyped(json, true),
    ...ValidationStringFromJSONTyped(json, true),
  }
}

export function ValidationStringOrNumberToJSON(value?: ValidationStringOrNumber | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  // @ts-ignore
  return { ...ValidationNumberToJSON(value), ...ValidationStringToJSON(value) }
}
