/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ValidationNumber
 */
export interface ValidationNumber {
  /**
   *
   * @type {number}
   * @memberof ValidationNumber
   */
  value: number
  /**
   *
   * @type {string}
   * @memberof ValidationNumber
   */
  message: string
}

export function ValidationNumberFromJSON(json: any): ValidationNumber {
  return ValidationNumberFromJSONTyped(json, false)
}

export function ValidationNumberFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ValidationNumber {
  if (json === undefined || json === null) {
    return json
  }
  return {
    value: json['value'],
    message: json['message'],
  }
}

export function ValidationNumberToJSON(value?: ValidationNumber | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    value: value.value,
    message: value.message,
  }
}
