/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ValidationMessages
 */
export interface ValidationMessages {
  /**
   *
   * @type {string}
   * @memberof ValidationMessages
   */
  maxlength?: string
  /**
   *
   * @type {string}
   * @memberof ValidationMessages
   */
  minlength?: string
  /**
   *
   * @type {string}
   * @memberof ValidationMessages
   */
  pattern?: string
  /**
   *
   * @type {string}
   * @memberof ValidationMessages
   */
  required?: string
  /**
   *
   * @type {string}
   * @memberof ValidationMessages
   */
  max?: string
  /**
   *
   * @type {string}
   * @memberof ValidationMessages
   */
  min?: string
}

export function ValidationMessagesFromJSON(json: any): ValidationMessages {
  return ValidationMessagesFromJSONTyped(json, false)
}

export function ValidationMessagesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ValidationMessages {
  if (json === undefined || json === null) {
    return json
  }
  return {
    maxlength: !exists(json, 'maxlength') ? undefined : json['maxlength'],
    minlength: !exists(json, 'minlength') ? undefined : json['minlength'],
    pattern: !exists(json, 'pattern') ? undefined : json['pattern'],
    required: !exists(json, 'required') ? undefined : json['required'],
    max: !exists(json, 'max') ? undefined : json['max'],
    min: !exists(json, 'min') ? undefined : json['min'],
  }
}

export function ValidationMessagesToJSON(value?: ValidationMessages | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    maxlength: value.maxlength,
    minlength: value.minlength,
    pattern: value.pattern,
    required: value.required,
    max: value.max,
    min: value.min,
  }
}
