/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ValidationField
 */
export interface ValidationField {
  /**
   *
   * @type {string}
   * @memberof ValidationField
   */
  field?: string
  /**
   *
   * @type {string}
   * @memberof ValidationField
   */
  message: string
}

export function ValidationFieldFromJSON(json: any): ValidationField {
  return ValidationFieldFromJSONTyped(json, false)
}

export function ValidationFieldFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ValidationField {
  if (json === undefined || json === null) {
    return json
  }
  return {
    field: !exists(json, 'field') ? undefined : json['field'],
    message: json['message'],
  }
}

export function ValidationFieldToJSON(value?: ValidationField | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    field: value.field,
    message: value.message,
  }
}
