/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  EmptyBodyResponse,
  EmptyBodyResponseFromJSON,
  EmptyBodyResponseFromJSONTyped,
  EmptyBodyResponseToJSON,
} from './'

/**
 *
 * @export
 * @interface VerifyComplaintResponse
 */
export interface VerifyComplaintResponse {
  /**
   *
   * @type {EmptyBodyResponse}
   * @memberof VerifyComplaintResponse
   */
  response?: EmptyBodyResponse
}

export function VerifyComplaintResponseFromJSON(json: any): VerifyComplaintResponse {
  return VerifyComplaintResponseFromJSONTyped(json, false)
}

export function VerifyComplaintResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VerifyComplaintResponse {
  if (json === undefined || json === null) {
    return json
  }
  return {
    response: !exists(json, 'response') ? undefined : EmptyBodyResponseFromJSON(json['response']),
  }
}

export function VerifyComplaintResponseToJSON(value?: VerifyComplaintResponse | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    response: EmptyBodyResponseToJSON(value.response),
  }
}
