/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  WidgetFieldsStack,
  WidgetFieldsStackFromJSON,
  WidgetFieldsStackFromJSONTyped,
  WidgetFieldsStackToJSON,
} from './'

/**
 *
 * @export
 * @interface WidgetFieldStack
 */
export interface WidgetFieldStack {
  /**
   *
   * @type {string}
   * @memberof WidgetFieldStack
   */
  widgetType: string
  /**
   *
   * @type {Array<{ [key: string]: WidgetFieldsStack; }>}
   * @memberof WidgetFieldStack
   */
  stack: Array<{ [key: string]: WidgetFieldsStack }>
}

export function WidgetFieldStackFromJSON(json: any): WidgetFieldStack {
  return WidgetFieldStackFromJSONTyped(json, false)
}

export function WidgetFieldStackFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WidgetFieldStack {
  if (json === undefined || json === null) {
    return json
  }
  return {
    widgetType: json['widgetType'],
    stack: (json['stack'] as Array<any>).map((item) =>
      mapValues(item, WidgetFieldsStackFromJSON),
    ),
  }
}

export function WidgetFieldStackToJSON(value?: WidgetFieldStack | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    widgetType: value.widgetType,
    stack: (value['stack'] as Array<any>).map((item) => mapValues(item, WidgetFieldsStackToJSON)),
  }
}
