/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface WidgetRestrict
 */
export interface WidgetRestrict {
  /**
   * Sort order:
   *  * `1` - As default, allow global widget for all pages
   *  * `2` - Allow global widget only for listed pages slugs
   *  * `3` - Disallow global widget for listed pages slugs
   * @type {number}
   * @memberof WidgetRestrict
   */
  filter?: WidgetRestrictFilterEnum
  /**
   *
   * @type {Array<string>}
   * @memberof WidgetRestrict
   */
  pages?: Array<string>
}

/**
 * @export
 * @enum {string}
 */
export enum WidgetRestrictFilterEnum {
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_3 = 3,
}

export function WidgetRestrictFromJSON(json: any): WidgetRestrict {
  return WidgetRestrictFromJSONTyped(json, false)
}

export function WidgetRestrictFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WidgetRestrict {
  if (json === undefined || json === null) {
    return json
  }
  return {
    filter: !exists(json, 'filter') ? undefined : json['filter'],
    pages: !exists(json, 'pages') ? undefined : json['pages'],
  }
}

export function WidgetRestrictToJSON(value?: WidgetRestrict | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    filter: value.filter,
    pages: value.pages,
  }
}
