/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  WidgetFieldOptionsMultipleOptions,
  WidgetFieldOptionsMultipleOptionsFromJSON,
  WidgetFieldOptionsMultipleOptionsFromJSONTyped,
  WidgetFieldOptionsMultipleOptionsToJSON,
} from './'

/**
 *
 * @export
 * @interface WidgetFieldOptionsMultiple
 */
export interface WidgetFieldOptionsMultiple {
  /**
   *
   * @type {string}
   * @memberof WidgetFieldOptionsMultiple
   */
  widgetType: string
  /**
   *
   * @type {Array<WidgetFieldOptionsMultipleOptions>}
   * @memberof WidgetFieldOptionsMultiple
   */
  options: Array<WidgetFieldOptionsMultipleOptions>
}

export function WidgetFieldOptionsMultipleFromJSON(json: any): WidgetFieldOptionsMultiple {
  return WidgetFieldOptionsMultipleFromJSONTyped(json, false)
}

export function WidgetFieldOptionsMultipleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WidgetFieldOptionsMultiple {
  if (json === undefined || json === null) {
    return json
  }
  return {
    widgetType: json['widgetType'],
    options: (json['options'] as Array<any>).map(WidgetFieldOptionsMultipleOptionsFromJSON),
  }
}

export function WidgetFieldOptionsMultipleToJSON(value?: WidgetFieldOptionsMultiple | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    widgetType: value.widgetType,
    options: (value.options as Array<any>).map(WidgetFieldOptionsMultipleOptionsToJSON),
  }
}
