/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface WidgetFieldText
 */
export interface WidgetFieldText {
  /**
   *
   * @type {string}
   * @memberof WidgetFieldText
   */
  widgetType: string
  /**
   *
   * @type {string}
   * @memberof WidgetFieldText
   */
  value: string
}

export function WidgetFieldTextFromJSON(json: any): WidgetFieldText {
  return WidgetFieldTextFromJSONTyped(json, false)
}

export function WidgetFieldTextFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WidgetFieldText {
  if (json === undefined || json === null) {
    return json
  }
  return {
    widgetType: json['widgetType'],
    value: json['value'],
  }
}

export function WidgetFieldTextToJSON(value?: WidgetFieldText | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    widgetType: value.widgetType,
    value: value.value,
  }
}
