/* tslint:disable */
/* eslint-disable */
/**
 * SITE API
 * API сайта ПИК Брокер
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface WidgetFieldPdf
 */
export interface WidgetFieldPdf {
  /**
   *
   * @type {string}
   * @memberof WidgetFieldPdf
   */
  widgetType: string
  /**
   *
   * @type {string}
   * @memberof WidgetFieldPdf
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof WidgetFieldPdf
   */
  src: string
}

export function WidgetFieldPdfFromJSON(json: any): WidgetFieldPdf {
  return WidgetFieldPdfFromJSONTyped(json, false)
}

export function WidgetFieldPdfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WidgetFieldPdf {
  if (json === undefined || json === null) {
    return json
  }
  return {
    widgetType: json['widgetType'],
    title: json['title'],
    src: json['src'],
  }
}

export function WidgetFieldPdfToJSON(value?: WidgetFieldPdf | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    widgetType: value.widgetType,
    title: value.title,
    src: value.src,
  }
}
